In [378]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [379]:
#Jupyter Notebook designed to define, experiment, & test various methods of handling NFL QB data in the hopes of determining the most accurate and plausible cortisol scores for each QB. Existing logic was eventually moved to the various .py files for pipeline usability.

In [380]:
pip install nflreadpy

Requirement already satisfied: nflreadpy in /opt/anaconda3/lib/python3.12/site-packages (0.1.6)
Requirement already satisfied: requests>=2.28.0 in /opt/anaconda3/lib/python3.12/site-packages (from nflreadpy) (2.32.3)
Requirement already satisfied: polars>=0.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from nflreadpy) (1.38.1)
Requirement already satisfied: platformdirs>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from nflreadpy) (3.10.0)
Requirement already satisfied: tqdm>=4.64.0 in /opt/anaconda3/lib/python3.12/site-packages (from nflreadpy) (4.66.5)
Requirement already satisfied: pydantic>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from nflreadpy) (2.8.2)
Requirement already satisfied: pydantic-settings>=2.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from nflreadpy) (2.13.1)
Requirement already satisfied: polars-runtime-32==1.38.1 in /opt/anaconda3/lib/python3.12/site-packages (from polars>=0.20.0->nflreadpy) (1.38.1)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic>=2.0.0->nflreadpy) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic>=2.0.0->nflreadpy) (2.20.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic>=2.0.0->nflreadpy) (4.15.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic-settings>=2.0.0->nflreadpy) (0.21.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic-settings>=2.0.0->nflreadpy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.28.0->nflreadpy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.28.0->nflreadpy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.28.0->nflreadpy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.28.0->nflreadpy) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

In [381]:
import nflreadpy as nfl

In [382]:
player_stats_2023 = nfl.load_player_stats([2023])
player_stats_2023

shape: (18_643, 115)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ gwfg_bloc ┆ gwfg_dist ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ ked       ┆ ance      ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002649 ┆ M.Staffor ┆ Matthew   ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 14.46     ┆ 14.46     │
│ 8         ┆ d         ┆ Stafford  ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003864 ┆ B.Willis  ┆ Brayden   ┆ TE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Willis    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003898 ┆ C.Conner  ┆ Chamarri  ┆ DB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆ Conner    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003900 ┆ F.Anudike ┆ Felix Anu ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆ -Uzomah   ┆ dike-Uzom ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ah        ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003906 ┆ R.Rice    ┆ Rashee    ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 4.4       ┆ 10.4      │
│ 7         ┆           ┆ Rice      ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [383]:
player_stats_23 = player_stats_2023.to_pandas()
player_stats_23.to_csv("../data/raw/player_stats_2023_season.csv", index=False)

In [384]:
player_stats_2023.shape

(18643, 115)

In [385]:
player_stats_23

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,...,pat_missed,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,...,0,0,NaN,0,0,0,0,0,0.00,0.00
1,00-0023853,M.Prater,Matt Prater,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_ARI_WAS,...,0,0,1.0,0,0,0,0,0,0.00,0.00
2,00-0025565,N.Folk,Nick Folk,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TEN_NO,...,0,0,NaN,0,0,0,0,0,0.00,0.00
3,00-0026190,C.Campbell,Calais Campbell,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CAR_ATL,...,0,0,NaN,0,0,0,0,0,0.00,0.00
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,...,0,0,NaN,0,0,0,0,0,14.46,14.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18638,00-0038643,B.Willis,Brayden Willis,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,0.00,0.00
18639,00-0038982,C.Conner,Chamarri Conner,DB,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,0.00,0.00
18640,00-0039006,F.Anudike-Uzomah,Felix Anudike-Uzomah,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,0.00,0.00
18641,00-0039067,R.Rice,Rashee Rice,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,4.40,10.40
18642,None,None,None,None,None,None,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,0.00,0.00

In [386]:
player_stats_23.shape

(18643, 115)

In [387]:
qb_stats_23 = player_stats_23[player_stats_23["position"]=="QB"]
qb_stats_23

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,...,pat_missed,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,...,0,0,NaN,0,0,0,0,0,0.00,0.00
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,...,0,0,NaN,0,0,0,0,0,14.46,14.46
15,00-0028118,T.Taylor,Tyrod Taylor,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_DAL_NYG,...,0,0,NaN,0,0,0,0,0,0.24,0.24
22,00-0029263,R.Wilson,Russell Wilson,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LV_DEN,...,0,0,NaN,0,0,0,0,0,15.18,15.18
29,00-0029604,K.Cousins,Kirk Cousins,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TB_MIN,...,0,0,NaN,0,0,0,0,0,16.46,16.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18478,00-0033873,P.Mahomes,Patrick Mahomes,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,21,POST,2023_21_KC_BAL,...,0,0,NaN,0,0,0,0,0,15.14,15.14
18494,00-0034796,L.Jackson,Lamar Jackson,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,21,POST,2023_21_KC_BAL,...,0,0,NaN,0,0,0,0,0,17.58,18.58
18556,00-0037834,B.Purdy,Brock Purdy,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,21,POST,2023_21_DET_SF,...,0,0,NaN,0,0,0,0,0,17.48,17.48
18589,00-0033873,P.Mahomes,Patrick Mahomes,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,25.92,25.92
18631,00-0037834,B.Purdy,Brock Purdy,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,NaN,0,0,0,0,0,15.40,15.40

In [388]:
qb_stats_23.shape

(690, 115)

In [389]:
qb_stats_23 = qb_stats_23[qb_stats_23["season_type"]=="REG"]
qb_stats_23

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,...,pat_missed,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,...,0,0,NaN,0,0,0,0,0,0.00,0.00
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,...,0,0,NaN,0,0,0,0,0,14.46,14.46
15,00-0028118,T.Taylor,Tyrod Taylor,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_DAL_NYG,...,0,0,NaN,0,0,0,0,0,0.24,0.24
22,00-0029263,R.Wilson,Russell Wilson,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LV_DEN,...,0,0,NaN,0,0,0,0,0,15.18,15.18
29,00-0029604,K.Cousins,Kirk Cousins,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TB_MIN,...,0,0,NaN,0,0,0,0,0,16.46,16.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17665,00-0038476,T.DeVito,Tommy DeVito,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,18,REG,2023_18_PHI_NYG,...,0,0,NaN,0,0,0,0,0,0.56,0.56
17698,00-0038579,A.O'Connell,Aidan O'Connell,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,18,REG,2023_18_DEN_LV,...,0,0,NaN,0,0,0,0,0,17.86,17.86
17700,00-0038582,C.Tune,Clayton Tune,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,18,REG,2023_18_SEA_ARI,...,0,0,NaN,0,0,0,0,0,0.10,0.10
17798,00-0039150,B.Young,Bryce Young,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,18,REG,2023_18_TB_CAR,...,0,0,NaN,0,0,0,0,0,4.16,4.16
17802,00-0039163,C.Stroud,C.J. Stroud,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,18,REG,2023_18_HOU_IND,...,0,0,NaN,0,0,0,0,0,20.56,20.56

In [390]:
#Calculate valuable totals and condense the QB table 
qb_season_stats = (
    qb_stats_23.groupby(
        ["player_id", "player_name", "player_display_name", "headshot_url", "season", "team"],
        as_index=False
    )
    .agg(
        total_passing_yds=("passing_yards", "sum"),
        total_passing_tds=("passing_tds", "sum"),
        total_rushing_tds=("rushing_tds", "sum"),
        total_attempts=("attempts", "sum"),
        total_completions=("completions", "sum"),
        total_carries=("carries", "sum"),
        total_ints=("passing_interceptions", "sum"),
        total_sack_fumbles=("sack_fumbles", "sum"),
        total_sack_fumbles_lost=("sack_fumbles_lost", "sum"),
        total_rushing_fumbles=("rushing_fumbles", "sum"),
        total_rushing_fumbles_lost=("rushing_fumbles_lost", "sum"),
        total_sacks=("sacks_suffered", "sum"),
        total_sack_yds_lost=("sack_yards_lost", "sum"),
        total_air_yds=("passing_air_yards", "sum"),
        total_epa=("passing_epa", "sum"),
        total_first_downs=("passing_first_downs", "sum"),
        total_2pt_passing_convs=("passing_2pt_conversions", "sum"),
        total_2pt_rushing_convs=("rushing_2pt_conversions", "sum"),
        total_fantasy_points=("fantasy_points", "sum"),
    )
)

In [391]:
qb_season_stats

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_rushing_fumbles,total_rushing_fumbles_lost,total_sacks,total_sack_yds_lost,total_air_yds,total_epa,total_first_downs,total_2pt_passing_convs,total_2pt_rushing_convs,total_fantasy_points
0,00-0023459,A.Rodgers,Aaron Rodgers,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,0,0,0,1,...,0,0,1,-10,17,-2.031960,0,0,0,0.00
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,1,0,8,-57,1910,-0.554587,60,1,0,100.84
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,0,0,30,-205,4033,54.191108,187,1,0,243.10
3,00-0026625,B.Hoyer,Brian Hoyer,https://static.www.nfl.com/image/private/f_aut...,2023,LV,231,0,0,42,...,0,0,1,-8,344,-8.780773,14,0,0,4.94
4,00-0027948,B.Gabbert,Blaine Gabbert,https://static.www.nfl.com/image/private/f_aut...,2023,KC,185,0,0,35,...,0,0,1,-9,198,-16.143287,8,0,0,5.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,00-0038598,J.Hall,Jaren Hall,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,168,0,0,20,...,0,0,4,-28,156,-12.676043,7,0,0,2.12
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,2,0,62,-477,4009,-159.273442,135,1,1,156.38
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,2,2,28,-185,2688,-12.833491,81,1,0,102.02
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,2,1,38,-331,4481,61.985173,188,0,1,275.02
81,00-0039164,A.Richardson,Anthony Richardson,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,577,3,4,84,...,2,1,7,-29,676,6.693791,31,2,0,72.68

In [392]:
qb_season_stats.sort_values(by="total_passing_yds", ascending=False).head(10)

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_rushing_fumbles,total_rushing_fumbles_lost,total_sacks,total_sack_yds_lost,total_air_yds,total_epa,total_first_downs,total_2pt_passing_convs,total_2pt_rushing_convs,total_fantasy_points
54,00-0036212,T.Tagovailoa,Tua Tagovailoa,https://static.www.nfl.com/image/upload/f_auto...,2023,MIA,4624,29,0,560,...,9,4,29,-171,4283,121.674346,223,0,0,270.36
24,00-0033106,J.Goff,Jared Goff,https://static.www.nfl.com/image/upload/f_auto...,2023,DET,4575,30,2,605,...,2,2,30,-197,4064,80.942251,227,2,0,289.10
23,00-0033077,D.Prescott,Dak Prescott,https://static.www.nfl.com/image/upload/f_auto...,2023,DAL,4516,36,2,590,...,1,1,39,-255,4579,120.795065,224,2,0,342.84
43,00-0034857,J.Allen,Josh Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,4306,29,15,579,...,4,3,24,-152,5022,91.692798,200,3,0,392.64
66,00-0037834,B.Purdy,Brock Purdy,https://static.www.nfl.com/image/upload/f_auto...,2023,SF,4280,31,2,444,...,2,0,28,-153,3636,143.753559,193,0,0,295.60
31,00-0033873,P.Mahomes,Patrick Mahomes,https://static.www.nfl.com/image/upload/f_auto...,2023,KC,4183,27,0,597,...,1,0,27,-186,3873,50.961516,206,0,0,280.22
55,00-0036264,J.Love,Jordan Love,https://static.www.nfl.com/image/upload/f_auto...,2023,GB,4159,32,4,579,...,4,2,30,-242,4897,88.023584,209,2,0,319.06
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,2,1,38,-331,4481,61.985173,188,0,1,275.02
42,00-0034855,B.Mayfield,Baker Mayfield,https://static.www.nfl.com/image/upload/f_auto...,2023,TB,4044,28,1,566,...,2,0,40,-232,4844,49.825179,188,2,0,274.06
62,00-0036971,T.Lawrence,Trevor Lawrence,https://static.www.nfl.com/image/upload/f_auto...,2023,JAX,4016,21,4,564,...,3,2,35,-224,4613,-0.063686,179,1,0,262.54

In [393]:
qb_season_stats.duplicated().sum()

0

In [394]:
qb_season_stats

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_rushing_fumbles,total_rushing_fumbles_lost,total_sacks,total_sack_yds_lost,total_air_yds,total_epa,total_first_downs,total_2pt_passing_convs,total_2pt_rushing_convs,total_fantasy_points
0,00-0023459,A.Rodgers,Aaron Rodgers,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,0,0,0,1,...,0,0,1,-10,17,-2.031960,0,0,0,0.00
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,1,0,8,-57,1910,-0.554587,60,1,0,100.84
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,0,0,30,-205,4033,54.191108,187,1,0,243.10
3,00-0026625,B.Hoyer,Brian Hoyer,https://static.www.nfl.com/image/private/f_aut...,2023,LV,231,0,0,42,...,0,0,1,-8,344,-8.780773,14,0,0,4.94
4,00-0027948,B.Gabbert,Blaine Gabbert,https://static.www.nfl.com/image/private/f_aut...,2023,KC,185,0,0,35,...,0,0,1,-9,198,-16.143287,8,0,0,5.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,00-0038598,J.Hall,Jaren Hall,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,168,0,0,20,...,0,0,4,-28,156,-12.676043,7,0,0,2.12
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,2,0,62,-477,4009,-159.273442,135,1,1,156.38
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,2,2,28,-185,2688,-12.833491,81,1,0,102.02
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,2,1,38,-331,4481,61.985173,188,0,1,275.02
81,00-0039164,A.Richardson,Anthony Richardson,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,577,3,4,84,...,2,1,7,-29,676,6.693791,31,2,0,72.68

In [395]:
qb_season_stats.shape

(82, 25)

In [396]:
#dropback column for simplifying further calculations 
qb_season_stats["total_dropbacks"] = qb_season_stats['total_attempts'] + qb_season_stats['total_sacks']
qb_season_stats["total_fumbles_lost"] = qb_season_stats['total_sack_fumbles_lost'] + qb_season_stats['total_rushing_fumbles_lost']
qb_season_stats["total_tds"] = qb_season_stats['total_passing_tds'] + qb_season_stats['total_rushing_tds']

#Turnover Risk factors 
qb_season_stats["int_rate"] = qb_season_stats['total_ints'] / qb_season_stats['total_attempts']
qb_season_stats["fumble_lost_rate"] =  qb_season_stats['total_fumbles_lost'] / qb_season_stats['total_dropbacks']

#Drive Sustainability
qb_season_stats["first_down_rate"] = qb_season_stats['total_first_downs'] / qb_season_stats['total_attempts']
qb_season_stats["completion_rate"] = qb_season_stats['total_completions'] / qb_season_stats['total_attempts']
qb_season_stats["sack_rate"] = qb_season_stats['total_sacks'] / qb_season_stats['total_dropbacks']
qb_season_stats["sack_yards_per_sack"] = qb_season_stats['total_sack_yds_lost'] / qb_season_stats['total_sacks'].replace(0, np.nan)

#Offensive Success
qb_season_stats["td_per_attempt"] = qb_season_stats['total_tds'] / qb_season_stats['total_attempts']
qb_season_stats['epa_per_dropback'] = qb_season_stats['total_epa'] / qb_season_stats['total_dropbacks']
qb_season_stats['yards_per_attempt'] = qb_season_stats['total_passing_yds'] / qb_season_stats['total_attempts']

In [397]:
qb_season_stats.sort_values(by='total_passing_yds', ascending=False)

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_tds,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
54,00-0036212,T.Tagovailoa,Tua Tagovailoa,https://static.www.nfl.com/image/upload/f_auto...,2023,MIA,4624,29,0,560,...,29,0.025000,0.008489,0.398214,0.692857,0.049236,-5.896552,0.051786,0.206578,8.257143
24,00-0033106,J.Goff,Jared Goff,https://static.www.nfl.com/image/upload/f_auto...,2023,DET,4575,30,2,605,...,32,0.019835,0.006299,0.375207,0.672727,0.047244,-6.566667,0.052893,0.127468,7.561983
23,00-0033077,D.Prescott,Dak Prescott,https://static.www.nfl.com/image/upload/f_auto...,2023,DAL,4516,36,2,590,...,38,0.015254,0.003180,0.379661,0.694915,0.062003,-6.538462,0.064407,0.192043,7.654237
43,00-0034857,J.Allen,Josh Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,4306,29,15,579,...,44,0.031088,0.006633,0.345423,0.664940,0.039801,-6.333333,0.075993,0.152061,7.436960
66,00-0037834,B.Purdy,Brock Purdy,https://static.www.nfl.com/image/upload/f_auto...,2023,SF,4280,31,2,444,...,33,0.024775,0.004237,0.434685,0.693694,0.059322,-5.464286,0.074324,0.304563,9.639640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11,00-0030533,M.Barkley,Matt Barkley,https://static.www.nfl.com/image/private/f_aut...,2023,JAX,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,00-0033958,N.Peterman,Nathan Peterman,https://static.www.nfl.com/image/private/f_aut...,2023,CHI,0,0,0,0,...,0,NaN,0.000000,NaN,NaN,1.000000,-5.000000,NaN,-0.094426,NaN
60,00-0036928,K.Trask,Kyle Trask,https://static.www.nfl.com/image/upload/f_auto...,2023,TB,0,0,0,1,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,-1.880303,0.000000
39,00-0034577,K.Allen,Kyle Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,0,0,0,0,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,00-0023459,A.Rodgers,Aaron Rodgers,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,0,0,0,1,...,0,0.000000,0.000000,0.000000,0.000000,0.500000,-10.000000,0.000000,-1.015980,0.000000

In [398]:
qb_season_stats.columns

Index(['player_id', 'player_name', 'player_display_name', 'headshot_url',
       'season', 'team', 'total_passing_yds', 'total_passing_tds',
       'total_rushing_tds', 'total_attempts', 'total_completions',
       'total_carries', 'total_ints', 'total_sack_fumbles',
       'total_sack_fumbles_lost', 'total_rushing_fumbles',
       'total_rushing_fumbles_lost', 'total_sacks', 'total_sack_yds_lost',
       'total_air_yds', 'total_epa', 'total_first_downs',
       'total_2pt_passing_convs', 'total_2pt_rushing_convs',
       'total_fantasy_points', 'total_dropbacks', 'total_fumbles_lost',
       'total_tds', 'int_rate', 'fumble_lost_rate', 'first_down_rate',
       'completion_rate', 'sack_rate', 'sack_yards_per_sack', 'td_per_attempt',
       'epa_per_dropback', 'yards_per_attempt'],
      dtype='object')

In [399]:
qb_season_stats['total_attempts'].mean()

222.82926829268294

In [400]:
qb_season_stats['total_dropbacks'].mean()

239.8780487804878

In [401]:
qb_season_stats['total_dropbacks'].describe()

count     82.000000
mean     239.878049
std      220.548272
min        0.000000
25%       41.000000
50%      173.500000
75%      417.750000
max      677.000000
Name: total_dropbacks, dtype: float64

In [402]:
qb_season_stats['total_attempts'].describe()

count     82.000000
mean     222.829268
std      206.726204
min        0.000000
25%       38.250000
50%      156.500000
75%      383.500000
max      612.000000
Name: total_attempts, dtype: float64

In [403]:
qb_season_stats.shape

(82, 37)

In [404]:
#Removes QBs that didn't take a single snap during the season
qb_season_stats = qb_season_stats[qb_season_stats["total_attempts"] > 0]

In [405]:
qb_season_stats

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_tds,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
0,00-0023459,A.Rodgers,Aaron Rodgers,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,0,0,0,1,...,0,0.000000,0.000000,0.000000,0.000000,0.500000,-10.000000,0.000000,-1.015980,0.000000
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,13,0.039216,0.004717,0.294118,0.602941,0.037736,-7.125000,0.063725,-0.002616,7.921569
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,24,0.021113,0.000000,0.358925,0.625720,0.054446,-6.833333,0.046065,0.098350,7.610365
3,00-0026625,B.Hoyer,Brian Hoyer,https://static.www.nfl.com/image/private/f_aut...,2023,LV,231,0,0,42,...,0,0.047619,0.000000,0.333333,0.547619,0.023256,-8.000000,0.000000,-0.204204,5.500000
4,00-0027948,B.Gabbert,Blaine Gabbert,https://static.www.nfl.com/image/private/f_aut...,2023,KC,185,0,0,35,...,0,0.085714,0.000000,0.228571,0.514286,0.027778,-9.000000,0.000000,-0.448425,5.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,00-0038598,J.Hall,Jaren Hall,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,168,0,0,20,...,0,0.050000,0.083333,0.350000,0.650000,0.166667,-7.000000,0.000000,-0.528168,8.400000
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,11,0.018975,0.010187,0.256167,0.597723,0.105263,-7.693548,0.020873,-0.270413,5.459203
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,9,0.015686,0.014134,0.317647,0.584314,0.098940,-6.607143,0.035294,-0.045348,7.090196
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,26,0.010020,0.007449,0.376754,0.639279,0.070764,-8.710526,0.052104,0.115429,8.232465
81,00-0039164,A.Richardson,Anthony Richardson,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,577,3,4,84,...,7,0.011905,0.010989,0.369048,0.595238,0.076923,-4.142857,0.083333,0.073558,6.869048

In [406]:
qb_season_stats.shape

(78, 37)

In [407]:
qb_season_stats = qb_season_stats[qb_season_stats["total_dropbacks"] >= 200]

In [408]:
qb_season_stats

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_tds,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,13,0.039216,0.004717,0.294118,0.602941,0.037736,-7.125000,0.063725,-0.002616,7.921569
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,24,0.021113,0.000000,0.358925,0.625720,0.054446,-6.833333,0.046065,0.098350,7.610365
8,00-0029263,R.Wilson,Russell Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,DEN,3070,26,3,447,...,29,0.017897,0.010163,0.304251,0.664430,0.091463,-5.733333,0.064877,-0.030848,6.868009
9,00-0029604,K.Cousins,Kirk Cousins,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,2331,18,0,311,...,18,0.016077,0.012195,0.363344,0.694534,0.051829,-6.470588,0.057878,0.113119,7.495177
10,00-0029701,R.Tannehill,Ryan Tannehill,https://static.www.nfl.com/image/private/f_aut...,2023,TEN,1616,4,1,230,...,5,0.030435,0.000000,0.321739,0.647826,0.122137,-7.187500,0.021739,-0.087276,7.026087
12,00-0030565,G.Smith,Geno Smith,https://static.www.nfl.com/image/upload/f_auto...,2023,SEA,3624,20,1,499,...,21,0.018036,0.005660,0.338677,0.647295,0.058491,-7.451613,0.042084,0.065182,7.262525
14,00-0031280,D.Carr,Derek Carr,https://static.www.nfl.com/image/upload/f_auto...,2023,NO,3878,25,0,548,...,25,0.014599,0.005181,0.337591,0.684307,0.053541,-7.032258,0.045620,0.048403,7.076642
23,00-0033077,D.Prescott,Dak Prescott,https://static.www.nfl.com/image/upload/f_auto...,2023,DAL,4516,36,2,590,...,38,0.015254,0.003180,0.379661,0.694915,0.062003,-6.538462,0.064407,0.192043,7.654237
24,00-0033106,J.Goff,Jared Goff,https://static.www.nfl.com/image/upload/f_auto...,2023,DET,4575,30,2,605,...,32,0.019835,0.006299,0.375207,0.672727,0.047244,-6.566667,0.052893,0.127468,7.561983
31,00-0033873,P.Mahomes,Patrick Mahomes,https://static.www.nfl.com/image/upload/f_auto...,2023,KC,4183,27,0,597,...,27,0.023451,0.004808,0.345059,0.671692,0.043269,-6.888889,0.045226,0.081669,7.006700
33,00-0033949,J.Dobbs,Joshua Dobbs,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1569,8,3,266,...,11,0.018797,0.014134,0.308271,0.627820,0.060071,-7.411765,0.041353,-0.174772,5.898496
41,00-0034796,L.Jackson,Lamar Jackson,https://static.www.nfl.com/image/upload/f_auto...,2023,BAL,3678,24,5,457,...,29,0.015317,0.012146,0.365427,0.671772,0.074899,-5.891892,0.063457,0.119578,8.048140
42,00-0034855,B.Mayfield,Baker Mayfield,https://static.www.nfl.com/image/upload/f_auto...,2023,TB,4044,28,1,566,...,29,0.017668,0.004950,0.332155,0.643110,0.066007,-5.800000,0.051237,0.082220,7.144876
43,00-0034857,J.Allen,Josh Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,4306,29,15,579,...,44,0.031088,0.006633,0.345423,0.664940,0.039801,-6.333333,0.075993,0.152061,7.436960
46,00-0035100,J.Browning,Jake Browning,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,1936,12,3,243,...,15,0.028807,0.000000,0.382716,0.703704,0.089888,-7.041667,0.061728,0.087461,7.967078
47,00-0035228,K.Murray,Kyler Murray,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1799,10,3,268,...,13,0.018657,0.000000,0.332090,0.656716,0.062937,-6.611111,0.048507,-0.058274,6.712687
50,00-0035289,G.Minshew,Gardner Minshew,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,3305,15,3,490,...,18,0.018367,0.009542,0.300000,0.622449,0.064885,-5.500000,0.036735,-0.012582,6.744898
54,00-0036212,T.Tagovailoa,Tua Tagovailoa,https://static.www.nfl.com/image/upload/f_auto...,2023,MIA,4624,29,0,560,...,29,0.025000,0.008489,0.398214,0.692857,0.049236,-5.896552,0.051786,0.206578,8.257143
55,00-0036264,J.Love,Jordan Love,https://static.www.nfl.com/image/upload/f_auto...,2023,GB,4159,32,4,579,...,36,0.018998,0.004926,0.360967,0.642487,0.049261,-8.066667,0.062176,0.144538,7.183074
56,00-0036355,J.Herbert,Justin Herbert,https://static.www.nfl.com/image/upload/f_auto...,2023,LAC,3134,20,3,456,...,23,0.015351,0.002062,0.328947,0.651316,0.059794,-8.034483,0.050439,0.057561,6.872807
57,00-0036389,J.Hurts,Jalen Hurts,https://static.www.nfl.com/image/upload/f_auto...,2023,PHI,3858,23,15,538,...,38,0.027881,0.008711,0.343866,0.654275,0.062718,-6.166667,0.070632,0.108684,7.171004
58,00-0036442,J.Burrow,Joe Burrow,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,2309,15,0,365,...,15,0.016438,0.002571,0.317808,0.668493,0.061697,-7.500000,0.041096,0.015668,6.326027
61,00-0036945,J.Fields,Justin Fields,https://static.www.nfl.com/image/upload/f_auto...,2023,CHI,2562,16,4,370,...,20,0.024324,0.009662,0.327027,0.613514,0.106280,-6.477273,0.054054,-0.092248,6.924324
62,00-0036971,T.Lawrence,Trevor Lawrence,https://static.www.nfl.com/image/upload/f_auto...,2023,JAX,4016,21,4,564,...,25,0.024823,0.011686,0.317376,0.656028,0.058431,-6.400000,0.044326,-0.000106,7.120567
63,00-0036972,M.Jones,Mac Jones,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,2120,10,0,345,...,10,0.034783,0.005450,0.289855,0.649275,0.059946,-5.772727,0.028986,-0.149051,6.144928
64,00-0037013,Z.Wilson,Zach Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,2271,8,0,368,...,8,0.019022,0.016908,0.282609,0.600543,0.111111,-7.391304,0.021739,-0.244430,6.171196
65,00-0037077,S.Howell,Sam Howell,https://static.www.nfl.com/image/upload/f_auto...,2023,WAS,3946,21,5,612,...,26,0.034314,0.002954,0.294118,0.633987,0.096012,-6.907692,0.042484,-0.152962,6.447712
66,00-0037834,B.Purdy,Brock Purdy,https://static.www.nfl.com/image/upload/f_auto...,2023,SF,4280,31,2,444,...,33,0.024775,0.004237,0.434685,0.693694,0.059322,-5.464286,0.074324,0.304563,9.639640
67,00-0038102,K.Pickett,Kenny Pickett,https://static.www.nfl.com/image/upload/f_auto...,2023,PIT,2070,6,1,324,...,7,0.012346,0.000000,0.283951,0.620370,0.066282,-7.521739,0.021605,-0.118699,6.388889
68,00-0038108,B.Zappe,Bailey Zappe,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,1272,6,1,212,...,7,0.042453,0.004219,0.250000,0.599057,0.105485,-7.640000,0.033019,-0.345128,6.000000
69,00-0038122,D.Ridder,Desmond Ridder,https://static.www.nfl.com/image/upload/f_auto...,2023,ATL,2836,12,5,388,...,17,0.030928,0.016706,0.353093,0.641753,0.073986,-6.354839,0.043814,-0.076947,7.309278
73,00-0038476,T.DeVito,Tommy DeVito,https://static.www.nfl.com/image/upload/f_auto...,2023,NYG,1101,8,1,178,...,9,0.016854,0.004651,0.258427,0.640449,0.172093,-5.297297,0.050562,-0.229406,6.185393
74,00-0038579,A.O'Connell,Aidan O'Connell,https://static.www.nfl.com/image/upload/f_auto...,2023,LV,2218,12,1,343,...,13,0.020408,0.005450,0.311953,0.620991,0.065395,-7.208333,0.037901,-0.048500,6.466472
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,11,0.018975,0.010187,0.256167,0.597723,0.105263,-7.693548,0.020873,-0.270413,5.459203
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,9,0.015686,0.014134,0.317647,0.584314,0.098940,-6.607143,0.035294,-0.045348,7.090196
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,26,0.010020,0.007449,0.376754,0.639279,0.070764,-8.710526,0.052104,0.115429,8.232465

In [409]:
qb_season_stats.shape

(36, 37)

In [410]:
qb_season_stats.sort_values(by='total_passing_yds', ascending=False)

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_tds,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
54,00-0036212,T.Tagovailoa,Tua Tagovailoa,https://static.www.nfl.com/image/upload/f_auto...,2023,MIA,4624,29,0,560,...,29,0.025000,0.008489,0.398214,0.692857,0.049236,-5.896552,0.051786,0.206578,8.257143
24,00-0033106,J.Goff,Jared Goff,https://static.www.nfl.com/image/upload/f_auto...,2023,DET,4575,30,2,605,...,32,0.019835,0.006299,0.375207,0.672727,0.047244,-6.566667,0.052893,0.127468,7.561983
23,00-0033077,D.Prescott,Dak Prescott,https://static.www.nfl.com/image/upload/f_auto...,2023,DAL,4516,36,2,590,...,38,0.015254,0.003180,0.379661,0.694915,0.062003,-6.538462,0.064407,0.192043,7.654237
43,00-0034857,J.Allen,Josh Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,4306,29,15,579,...,44,0.031088,0.006633,0.345423,0.664940,0.039801,-6.333333,0.075993,0.152061,7.436960
66,00-0037834,B.Purdy,Brock Purdy,https://static.www.nfl.com/image/upload/f_auto...,2023,SF,4280,31,2,444,...,33,0.024775,0.004237,0.434685,0.693694,0.059322,-5.464286,0.074324,0.304563,9.639640
31,00-0033873,P.Mahomes,Patrick Mahomes,https://static.www.nfl.com/image/upload/f_auto...,2023,KC,4183,27,0,597,...,27,0.023451,0.004808,0.345059,0.671692,0.043269,-6.888889,0.045226,0.081669,7.006700
55,00-0036264,J.Love,Jordan Love,https://static.www.nfl.com/image/upload/f_auto...,2023,GB,4159,32,4,579,...,36,0.018998,0.004926,0.360967,0.642487,0.049261,-8.066667,0.062176,0.144538,7.183074
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,26,0.010020,0.007449,0.376754,0.639279,0.070764,-8.710526,0.052104,0.115429,8.232465
42,00-0034855,B.Mayfield,Baker Mayfield,https://static.www.nfl.com/image/upload/f_auto...,2023,TB,4044,28,1,566,...,29,0.017668,0.004950,0.332155,0.643110,0.066007,-5.800000,0.051237,0.082220,7.144876
62,00-0036971,T.Lawrence,Trevor Lawrence,https://static.www.nfl.com/image/upload/f_auto...,2023,JAX,4016,21,4,564,...,25,0.024823,0.011686,0.317376,0.656028,0.058431,-6.400000,0.044326,-0.000106,7.120567
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,24,0.021113,0.000000,0.358925,0.625720,0.054446,-6.833333,0.046065,0.098350,7.610365
65,00-0037077,S.Howell,Sam Howell,https://static.www.nfl.com/image/upload/f_auto...,2023,WAS,3946,21,5,612,...,26,0.034314,0.002954,0.294118,0.633987,0.096012,-6.907692,0.042484,-0.152962,6.447712
14,00-0031280,D.Carr,Derek Carr,https://static.www.nfl.com/image/upload/f_auto...,2023,NO,3878,25,0,548,...,25,0.014599,0.005181,0.337591,0.684307,0.053541,-7.032258,0.045620,0.048403,7.076642
57,00-0036389,J.Hurts,Jalen Hurts,https://static.www.nfl.com/image/upload/f_auto...,2023,PHI,3858,23,15,538,...,38,0.027881,0.008711,0.343866,0.654275,0.062718,-6.166667,0.070632,0.108684,7.171004
41,00-0034796,L.Jackson,Lamar Jackson,https://static.www.nfl.com/image/upload/f_auto...,2023,BAL,3678,24,5,457,...,29,0.015317,0.012146,0.365427,0.671772,0.074899,-5.891892,0.063457,0.119578,8.048140
12,00-0030565,G.Smith,Geno Smith,https://static.www.nfl.com/image/upload/f_auto...,2023,SEA,3624,20,1,499,...,21,0.018036,0.005660,0.338677,0.647295,0.058491,-7.451613,0.042084,0.065182,7.262525
50,00-0035289,G.Minshew,Gardner Minshew,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,3305,15,3,490,...,18,0.018367,0.009542,0.300000,0.622449,0.064885,-5.500000,0.036735,-0.012582,6.744898
56,00-0036355,J.Herbert,Justin Herbert,https://static.www.nfl.com/image/upload/f_auto...,2023,LAC,3134,20,3,456,...,23,0.015351,0.002062,0.328947,0.651316,0.059794,-8.034483,0.050439,0.057561,6.872807
8,00-0029263,R.Wilson,Russell Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,DEN,3070,26,3,447,...,29,0.017897,0.010163,0.304251,0.664430,0.091463,-5.733333,0.064877,-0.030848,6.868009
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,11,0.018975,0.010187,0.256167,0.597723,0.105263,-7.693548,0.020873,-0.270413,5.459203
69,00-0038122,D.Ridder,Desmond Ridder,https://static.www.nfl.com/image/upload/f_auto...,2023,ATL,2836,12,5,388,...,17,0.030928,0.016706,0.353093,0.641753,0.073986,-6.354839,0.043814,-0.076947,7.309278
61,00-0036945,J.Fields,Justin Fields,https://static.www.nfl.com/image/upload/f_auto...,2023,CHI,2562,16,4,370,...,20,0.024324,0.009662,0.327027,0.613514,0.106280,-6.477273,0.054054,-0.092248,6.924324
9,00-0029604,K.Cousins,Kirk Cousins,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,2331,18,0,311,...,18,0.016077,0.012195,0.363344,0.694534,0.051829,-6.470588,0.057878,0.113119,7.495177
58,00-0036442,J.Burrow,Joe Burrow,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,2309,15,0,365,...,15,0.016438,0.002571,0.317808,0.668493,0.061697,-7.500000,0.041096,0.015668,6.326027
64,00-0037013,Z.Wilson,Zach Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,2271,8,0,368,...,8,0.019022,0.016908,0.282609,0.600543,0.111111,-7.391304,0.021739,-0.244430,6.171196
74,00-0038579,A.O'Connell,Aidan O'Connell,https://static.www.nfl.com/image/upload/f_auto...,2023,LV,2218,12,1,343,...,13,0.020408,0.005450,0.311953,0.620991,0.065395,-7.208333,0.037901,-0.048500,6.466472
63,00-0036972,M.Jones,Mac Jones,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,2120,10,0,345,...,10,0.034783,0.005450,0.289855,0.649275,0.059946,-5.772727,0.028986,-0.149051,6.144928
67,00-0038102,K.Pickett,Kenny Pickett,https://static.www.nfl.com/image/upload/f_auto...,2023,PIT,2070,6,1,324,...,7,0.012346,0.000000,0.283951,0.620370,0.066282,-7.521739,0.021605,-0.118699,6.388889
46,00-0035100,J.Browning,Jake Browning,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,1936,12,3,243,...,15,0.028807,0.000000,0.382716,0.703704,0.089888,-7.041667,0.061728,0.087461,7.967078
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,9,0.015686,0.014134,0.317647,0.584314,0.098940,-6.607143,0.035294,-0.045348,7.090196
47,00-0035228,K.Murray,Kyler Murray,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1799,10,3,268,...,13,0.018657,0.000000,0.332090,0.656716,0.062937,-6.611111,0.048507,-0.058274,6.712687
10,00-0029701,R.Tannehill,Ryan Tannehill,https://static.www.nfl.com/image/private/f_aut...,2023,TEN,1616,4,1,230,...,5,0.030435,0.000000,0.321739,0.647826,0.122137,-7.187500,0.021739,-0.087276,7.026087
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,13,0.039216,0.004717,0.294118,0.602941,0.037736,-7.125000,0.063725,-0.002616,7.921569
33,00-0033949,J.Dobbs,Joshua Dobbs,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1569,8,3,266,...,11,0.018797,0.014134,0.308271,0.627820,0.060071,-7.411765,0.041353,-0.174772,5.898496
68,00-0038108,B.Zappe,Bailey Zappe,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,1272,6,1,212,...,7,0.042453,0.004219,0.250000,0.599057,0.105485,-7.640000,0.033019,-0.345128,6.000000
73,00-0038476,T.DeVito,Tommy DeVito,https://static.www.nfl.com/image/upload/f_auto...,2023,NYG,1101,8,1,178,...,9,0.016854,0.004651,0.258427,0.640449,0.172093,-5.297297,0.050562,-0.229406,6.185393

In [411]:
qb_season_stats.sort_values(by='td_per_attempt', ascending=False)

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_tds,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
43,00-0034857,J.Allen,Josh Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,4306,29,15,579,...,44,0.031088,0.006633,0.345423,0.664940,0.039801,-6.333333,0.075993,0.152061,7.436960
66,00-0037834,B.Purdy,Brock Purdy,https://static.www.nfl.com/image/upload/f_auto...,2023,SF,4280,31,2,444,...,33,0.024775,0.004237,0.434685,0.693694,0.059322,-5.464286,0.074324,0.304563,9.639640
57,00-0036389,J.Hurts,Jalen Hurts,https://static.www.nfl.com/image/upload/f_auto...,2023,PHI,3858,23,15,538,...,38,0.027881,0.008711,0.343866,0.654275,0.062718,-6.166667,0.070632,0.108684,7.171004
8,00-0029263,R.Wilson,Russell Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,DEN,3070,26,3,447,...,29,0.017897,0.010163,0.304251,0.664430,0.091463,-5.733333,0.064877,-0.030848,6.868009
23,00-0033077,D.Prescott,Dak Prescott,https://static.www.nfl.com/image/upload/f_auto...,2023,DAL,4516,36,2,590,...,38,0.015254,0.003180,0.379661,0.694915,0.062003,-6.538462,0.064407,0.192043,7.654237
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,13,0.039216,0.004717,0.294118,0.602941,0.037736,-7.125000,0.063725,-0.002616,7.921569
41,00-0034796,L.Jackson,Lamar Jackson,https://static.www.nfl.com/image/upload/f_auto...,2023,BAL,3678,24,5,457,...,29,0.015317,0.012146,0.365427,0.671772,0.074899,-5.891892,0.063457,0.119578,8.048140
55,00-0036264,J.Love,Jordan Love,https://static.www.nfl.com/image/upload/f_auto...,2023,GB,4159,32,4,579,...,36,0.018998,0.004926,0.360967,0.642487,0.049261,-8.066667,0.062176,0.144538,7.183074
46,00-0035100,J.Browning,Jake Browning,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,1936,12,3,243,...,15,0.028807,0.000000,0.382716,0.703704,0.089888,-7.041667,0.061728,0.087461,7.967078
9,00-0029604,K.Cousins,Kirk Cousins,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,2331,18,0,311,...,18,0.016077,0.012195,0.363344,0.694534,0.051829,-6.470588,0.057878,0.113119,7.495177
61,00-0036945,J.Fields,Justin Fields,https://static.www.nfl.com/image/upload/f_auto...,2023,CHI,2562,16,4,370,...,20,0.024324,0.009662,0.327027,0.613514,0.106280,-6.477273,0.054054,-0.092248,6.924324
24,00-0033106,J.Goff,Jared Goff,https://static.www.nfl.com/image/upload/f_auto...,2023,DET,4575,30,2,605,...,32,0.019835,0.006299,0.375207,0.672727,0.047244,-6.566667,0.052893,0.127468,7.561983
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,26,0.010020,0.007449,0.376754,0.639279,0.070764,-8.710526,0.052104,0.115429,8.232465
54,00-0036212,T.Tagovailoa,Tua Tagovailoa,https://static.www.nfl.com/image/upload/f_auto...,2023,MIA,4624,29,0,560,...,29,0.025000,0.008489,0.398214,0.692857,0.049236,-5.896552,0.051786,0.206578,8.257143
42,00-0034855,B.Mayfield,Baker Mayfield,https://static.www.nfl.com/image/upload/f_auto...,2023,TB,4044,28,1,566,...,29,0.017668,0.004950,0.332155,0.643110,0.066007,-5.800000,0.051237,0.082220,7.144876
73,00-0038476,T.DeVito,Tommy DeVito,https://static.www.nfl.com/image/upload/f_auto...,2023,NYG,1101,8,1,178,...,9,0.016854,0.004651,0.258427,0.640449,0.172093,-5.297297,0.050562,-0.229406,6.185393
56,00-0036355,J.Herbert,Justin Herbert,https://static.www.nfl.com/image/upload/f_auto...,2023,LAC,3134,20,3,456,...,23,0.015351,0.002062,0.328947,0.651316,0.059794,-8.034483,0.050439,0.057561,6.872807
47,00-0035228,K.Murray,Kyler Murray,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1799,10,3,268,...,13,0.018657,0.000000,0.332090,0.656716,0.062937,-6.611111,0.048507,-0.058274,6.712687
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,24,0.021113,0.000000,0.358925,0.625720,0.054446,-6.833333,0.046065,0.098350,7.610365
14,00-0031280,D.Carr,Derek Carr,https://static.www.nfl.com/image/upload/f_auto...,2023,NO,3878,25,0,548,...,25,0.014599,0.005181,0.337591,0.684307,0.053541,-7.032258,0.045620,0.048403,7.076642
31,00-0033873,P.Mahomes,Patrick Mahomes,https://static.www.nfl.com/image/upload/f_auto...,2023,KC,4183,27,0,597,...,27,0.023451,0.004808,0.345059,0.671692,0.043269,-6.888889,0.045226,0.081669,7.006700
62,00-0036971,T.Lawrence,Trevor Lawrence,https://static.www.nfl.com/image/upload/f_auto...,2023,JAX,4016,21,4,564,...,25,0.024823,0.011686,0.317376,0.656028,0.058431,-6.400000,0.044326,-0.000106,7.120567
69,00-0038122,D.Ridder,Desmond Ridder,https://static.www.nfl.com/image/upload/f_auto...,2023,ATL,2836,12,5,388,...,17,0.030928,0.016706,0.353093,0.641753,0.073986,-6.354839,0.043814,-0.076947,7.309278
65,00-0037077,S.Howell,Sam Howell,https://static.www.nfl.com/image/upload/f_auto...,2023,WAS,3946,21,5,612,...,26,0.034314,0.002954,0.294118,0.633987,0.096012,-6.907692,0.042484,-0.152962,6.447712
12,00-0030565,G.Smith,Geno Smith,https://static.www.nfl.com/image/upload/f_auto...,2023,SEA,3624,20,1,499,...,21,0.018036,0.005660,0.338677,0.647295,0.058491,-7.451613,0.042084,0.065182,7.262525
33,00-0033949,J.Dobbs,Joshua Dobbs,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1569,8,3,266,...,11,0.018797,0.014134,0.308271,0.627820,0.060071,-7.411765,0.041353,-0.174772,5.898496
58,00-0036442,J.Burrow,Joe Burrow,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,2309,15,0,365,...,15,0.016438,0.002571,0.317808,0.668493,0.061697,-7.500000,0.041096,0.015668,6.326027
74,00-0038579,A.O'Connell,Aidan O'Connell,https://static.www.nfl.com/image/upload/f_auto...,2023,LV,2218,12,1,343,...,13,0.020408,0.005450,0.311953,0.620991,0.065395,-7.208333,0.037901,-0.048500,6.466472
50,00-0035289,G.Minshew,Gardner Minshew,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,3305,15,3,490,...,18,0.018367,0.009542,0.300000,0.622449,0.064885,-5.500000,0.036735,-0.012582,6.744898
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,9,0.015686,0.014134,0.317647,0.584314,0.098940,-6.607143,0.035294,-0.045348,7.090196
68,00-0038108,B.Zappe,Bailey Zappe,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,1272,6,1,212,...,7,0.042453,0.004219,0.250000,0.599057,0.105485,-7.640000,0.033019,-0.345128,6.000000
63,00-0036972,M.Jones,Mac Jones,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,2120,10,0,345,...,10,0.034783,0.005450,0.289855,0.649275,0.059946,-5.772727,0.028986,-0.149051,6.144928
10,00-0029701,R.Tannehill,Ryan Tannehill,https://static.www.nfl.com/image/private/f_aut...,2023,TEN,1616,4,1,230,...,5,0.030435,0.000000,0.321739,0.647826,0.122137,-7.187500,0.021739,-0.087276,7.026087
64,00-0037013,Z.Wilson,Zach Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,2271,8,0,368,...,8,0.019022,0.016908,0.282609,0.600543,0.111111,-7.391304,0.021739,-0.244430,6.171196
67,00-0038102,K.Pickett,Kenny Pickett,https://static.www.nfl.com/image/upload/f_auto...,2023,PIT,2070,6,1,324,...,7,0.012346,0.000000,0.283951,0.620370,0.066282,-7.521739,0.021605,-0.118699,6.388889
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,11,0.018975,0.010187,0.256167,0.597723,0.105263,-7.693548,0.020873,-0.270413,5.459203

In [412]:
qb_season_stats.sort_values(by='total_dropbacks', ascending=False)

,player_id,player_name,player_display_name,headshot_url,season,team,total_passing_yds,total_passing_tds,total_rushing_tds,total_attempts,...,total_tds,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
65,00-0037077,S.Howell,Sam Howell,https://static.www.nfl.com/image/upload/f_auto...,2023,WAS,3946,21,5,612,...,26,0.034314,0.002954,0.294118,0.633987,0.096012,-6.907692,0.042484,-0.152962,6.447712
24,00-0033106,J.Goff,Jared Goff,https://static.www.nfl.com/image/upload/f_auto...,2023,DET,4575,30,2,605,...,32,0.019835,0.006299,0.375207,0.672727,0.047244,-6.566667,0.052893,0.127468,7.561983
23,00-0033077,D.Prescott,Dak Prescott,https://static.www.nfl.com/image/upload/f_auto...,2023,DAL,4516,36,2,590,...,38,0.015254,0.003180,0.379661,0.694915,0.062003,-6.538462,0.064407,0.192043,7.654237
31,00-0033873,P.Mahomes,Patrick Mahomes,https://static.www.nfl.com/image/upload/f_auto...,2023,KC,4183,27,0,597,...,27,0.023451,0.004808,0.345059,0.671692,0.043269,-6.888889,0.045226,0.081669,7.006700
55,00-0036264,J.Love,Jordan Love,https://static.www.nfl.com/image/upload/f_auto...,2023,GB,4159,32,4,579,...,36,0.018998,0.004926,0.360967,0.642487,0.049261,-8.066667,0.062176,0.144538,7.183074
42,00-0034855,B.Mayfield,Baker Mayfield,https://static.www.nfl.com/image/upload/f_auto...,2023,TB,4044,28,1,566,...,29,0.017668,0.004950,0.332155,0.643110,0.066007,-5.800000,0.051237,0.082220,7.144876
43,00-0034857,J.Allen,Josh Allen,https://static.www.nfl.com/image/upload/f_auto...,2023,BUF,4306,29,15,579,...,44,0.031088,0.006633,0.345423,0.664940,0.039801,-6.333333,0.075993,0.152061,7.436960
62,00-0036971,T.Lawrence,Trevor Lawrence,https://static.www.nfl.com/image/upload/f_auto...,2023,JAX,4016,21,4,564,...,25,0.024823,0.011686,0.317376,0.656028,0.058431,-6.400000,0.044326,-0.000106,7.120567
78,00-0039150,B.Young,Bryce Young,https://static.www.nfl.com/image/upload/f_auto...,2023,CAR,2877,11,0,527,...,11,0.018975,0.010187,0.256167,0.597723,0.105263,-7.693548,0.020873,-0.270413,5.459203
54,00-0036212,T.Tagovailoa,Tua Tagovailoa,https://static.www.nfl.com/image/upload/f_auto...,2023,MIA,4624,29,0,560,...,29,0.025000,0.008489,0.398214,0.692857,0.049236,-5.896552,0.051786,0.206578,8.257143
14,00-0031280,D.Carr,Derek Carr,https://static.www.nfl.com/image/upload/f_auto...,2023,NO,3878,25,0,548,...,25,0.014599,0.005181,0.337591,0.684307,0.053541,-7.032258,0.045620,0.048403,7.076642
57,00-0036389,J.Hurts,Jalen Hurts,https://static.www.nfl.com/image/upload/f_auto...,2023,PHI,3858,23,15,538,...,38,0.027881,0.008711,0.343866,0.654275,0.062718,-6.166667,0.070632,0.108684,7.171004
2,00-0026498,M.Stafford,Matthew Stafford,https://static.www.nfl.com/image/upload/f_auto...,2023,LA,3965,24,0,521,...,24,0.021113,0.000000,0.358925,0.625720,0.054446,-6.833333,0.046065,0.098350,7.610365
80,00-0039163,C.Stroud,C.J. Stroud,https://static.www.nfl.com/image/upload/f_auto...,2023,HOU,4108,23,3,499,...,26,0.010020,0.007449,0.376754,0.639279,0.070764,-8.710526,0.052104,0.115429,8.232465
12,00-0030565,G.Smith,Geno Smith,https://static.www.nfl.com/image/upload/f_auto...,2023,SEA,3624,20,1,499,...,21,0.018036,0.005660,0.338677,0.647295,0.058491,-7.451613,0.042084,0.065182,7.262525
50,00-0035289,G.Minshew,Gardner Minshew,https://static.www.nfl.com/image/upload/f_auto...,2023,IND,3305,15,3,490,...,18,0.018367,0.009542,0.300000,0.622449,0.064885,-5.500000,0.036735,-0.012582,6.744898
41,00-0034796,L.Jackson,Lamar Jackson,https://static.www.nfl.com/image/upload/f_auto...,2023,BAL,3678,24,5,457,...,29,0.015317,0.012146,0.365427,0.671772,0.074899,-5.891892,0.063457,0.119578,8.048140
8,00-0029263,R.Wilson,Russell Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,DEN,3070,26,3,447,...,29,0.017897,0.010163,0.304251,0.664430,0.091463,-5.733333,0.064877,-0.030848,6.868009
56,00-0036355,J.Herbert,Justin Herbert,https://static.www.nfl.com/image/upload/f_auto...,2023,LAC,3134,20,3,456,...,23,0.015351,0.002062,0.328947,0.651316,0.059794,-8.034483,0.050439,0.057561,6.872807
66,00-0037834,B.Purdy,Brock Purdy,https://static.www.nfl.com/image/upload/f_auto...,2023,SF,4280,31,2,444,...,33,0.024775,0.004237,0.434685,0.693694,0.059322,-5.464286,0.074324,0.304563,9.639640
69,00-0038122,D.Ridder,Desmond Ridder,https://static.www.nfl.com/image/upload/f_auto...,2023,ATL,2836,12,5,388,...,17,0.030928,0.016706,0.353093,0.641753,0.073986,-6.354839,0.043814,-0.076947,7.309278
64,00-0037013,Z.Wilson,Zach Wilson,https://static.www.nfl.com/image/upload/f_auto...,2023,NYJ,2271,8,0,368,...,8,0.019022,0.016908,0.282609,0.600543,0.111111,-7.391304,0.021739,-0.244430,6.171196
61,00-0036945,J.Fields,Justin Fields,https://static.www.nfl.com/image/upload/f_auto...,2023,CHI,2562,16,4,370,...,20,0.024324,0.009662,0.327027,0.613514,0.106280,-6.477273,0.054054,-0.092248,6.924324
58,00-0036442,J.Burrow,Joe Burrow,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,2309,15,0,365,...,15,0.016438,0.002571,0.317808,0.668493,0.061697,-7.500000,0.041096,0.015668,6.326027
74,00-0038579,A.O'Connell,Aidan O'Connell,https://static.www.nfl.com/image/upload/f_auto...,2023,LV,2218,12,1,343,...,13,0.020408,0.005450,0.311953,0.620991,0.065395,-7.208333,0.037901,-0.048500,6.466472
63,00-0036972,M.Jones,Mac Jones,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,2120,10,0,345,...,10,0.034783,0.005450,0.289855,0.649275,0.059946,-5.772727,0.028986,-0.149051,6.144928
67,00-0038102,K.Pickett,Kenny Pickett,https://static.www.nfl.com/image/upload/f_auto...,2023,PIT,2070,6,1,324,...,7,0.012346,0.000000,0.283951,0.620370,0.066282,-7.521739,0.021605,-0.118699,6.388889
9,00-0029604,K.Cousins,Kirk Cousins,https://static.www.nfl.com/image/upload/f_auto...,2023,MIN,2331,18,0,311,...,18,0.016077,0.012195,0.363344,0.694534,0.051829,-6.470588,0.057878,0.113119,7.495177
47,00-0035228,K.Murray,Kyler Murray,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1799,10,3,268,...,13,0.018657,0.000000,0.332090,0.656716,0.062937,-6.611111,0.048507,-0.058274,6.712687
79,00-0039152,W.Levis,Will Levis,https://static.www.nfl.com/image/upload/f_auto...,2023,TEN,1808,8,1,255,...,9,0.015686,0.014134,0.317647,0.584314,0.098940,-6.607143,0.035294,-0.045348,7.090196
33,00-0033949,J.Dobbs,Joshua Dobbs,https://static.www.nfl.com/image/upload/f_auto...,2023,ARI,1569,8,3,266,...,11,0.018797,0.014134,0.308271,0.627820,0.060071,-7.411765,0.041353,-0.174772,5.898496
46,00-0035100,J.Browning,Jake Browning,https://static.www.nfl.com/image/upload/f_auto...,2023,CIN,1936,12,3,243,...,15,0.028807,0.000000,0.382716,0.703704,0.089888,-7.041667,0.061728,0.087461,7.967078
10,00-0029701,R.Tannehill,Ryan Tannehill,https://static.www.nfl.com/image/private/f_aut...,2023,TEN,1616,4,1,230,...,5,0.030435,0.000000,0.321739,0.647826,0.122137,-7.187500,0.021739,-0.087276,7.026087
68,00-0038108,B.Zappe,Bailey Zappe,https://static.www.nfl.com/image/upload/f_auto...,2023,NE,1272,6,1,212,...,7,0.042453,0.004219,0.250000,0.599057,0.105485,-7.640000,0.033019,-0.345128,6.000000
73,00-0038476,T.DeVito,Tommy DeVito,https://static.www.nfl.com/image/upload/f_auto...,2023,NYG,1101,8,1,178,...,9,0.016854,0.004651,0.258427,0.640449,0.172093,-5.297297,0.050562,-0.229406,6.185393
1,00-0026158,J.Flacco,Joe Flacco,https://static.www.nfl.com/image/upload/f_auto...,2023,CLE,1616,13,0,204,...,13,0.039216,0.004717,0.294118,0.602941,0.037736,-7.125000,0.063725,-0.002616,7.921569

In [413]:
qb_season_stats[
[
"int_rate",
"fumble_lost_rate",
"first_down_rate",
"completion_rate",
"sack_rate",
"sack_yards_per_sack",
"td_per_attempt",
"epa_per_dropback",
"yards_per_attempt"
]
].describe()

,int_rate,fumble_lost_rate,first_down_rate,completion_rate,sack_rate,sack_yards_per_sack,td_per_attempt,epa_per_dropback,yards_per_attempt
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,0.022166,0.006668,0.330225,0.647147,0.072574,-6.764680,0.047798,-0.000529,7.078521
std,0.007662,0.004704,0.041060,0.031026,0.027625,0.808952,0.014758,0.146534,0.807672
min,0.010020,0.000000,0.250000,0.584314,0.037736,-8.710526,0.020873,-0.345128,5.459203
25%,0.016750,0.003959,0.303188,0.624902,0.057435,-7.396419,0.040297,-0.088519,6.461782
50%,0.019010,0.005450,0.330518,0.647560,0.062827,-6.722222,0.047286,0.007781,7.083419
75%,0.025720,0.009787,0.359436,0.669293,0.090282,-6.291667,0.058840,0.109793,7.511879
max,0.042453,0.016908,0.434685,0.703704,0.172093,-5.297297,0.075993,0.304563,9.639640

In [414]:
#Normalize all metrics and invert bad ones to ensure each metric value falls between 0 and 1, making each factor's contribution to the cortisol score proportional
good_metrics = [
    "first_down_rate",
    "completion_rate",
    "td_per_attempt",
    "epa_per_dropback",
    "yards_per_attempt"
]

bad_metrics = [
    "int_rate",
    "fumble_lost_rate",
    "sack_rate",
    "sack_yards_per_sack"
]

for good_metric in good_metrics:
    qb_season_stats[good_metric + "_norm"] = (qb_season_stats[good_metric] - min(qb_season_stats[good_metric])) / (max(qb_season_stats[good_metric]) - min(qb_season_stats[good_metric]))

for bad_metric in bad_metrics:
    qb_season_stats[bad_metric + "_norm"] = 1 - ((qb_season_stats[bad_metric] - min(qb_season_stats[bad_metric])) / (max(qb_season_stats[bad_metric]) - min(qb_season_stats[bad_metric])))

/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[good_metric + "_norm"] = (qb_season_stats[good_metric] - min(qb_season_stats[good_metric])) / (max(qb_season_stats[good_metric]) - min(qb_season_stats[good_metric]))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[good_metric + "_norm"] = (qb_season_stats[good_metric] - min(qb_season_stats[good_metric])) / (max(qb_season_stats[good_metric]) - min(qb_season_stats[good_metric]))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[good_metric + "_norm"] = (qb_season_stats[good_metric] - min(qb_season_stats[good_metric])) / (max(qb_season_stats[good_metric]) - min(qb_season_stats[good_metric]))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[good_metric + "_norm"] = (qb_season_stats[good_metric] - min(qb_season_stats[good_metric])) / (max(qb_season_stats[good_metric]) - min(qb_season_stats[good_metric]))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[good_metric + "_norm"] = (qb_season_stats[good_metric] - min(qb_season_stats[good_metric])) / (max(qb_season_stats[good_metric]) - min(qb_season_stats[good_metric]))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[bad_metric + "_norm"] = 1 - ((qb_season_stats[bad_metric] - min(qb_season_stats[bad_metric])) / (max(qb_season_stats[bad_metric]) - min(qb_season_stats[bad_metric])))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[bad_metric + "_norm"] = 1 - ((qb_season_stats[bad_metric] - min(qb_season_stats[bad_metric])) / (max(qb_season_stats[bad_metric]) - min(qb_season_stats[bad_metric])))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[bad_metric + "_norm"] = 1 - ((qb_season_stats[bad_metric] - min(qb_season_stats[bad_metric])) / (max(qb_season_stats[bad_metric]) - min(qb_season_stats[bad_metric])))
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/1788363790.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_season_stats[bad_metric + "_norm"] = 1 - ((qb_season_stats[bad_metric] - min(qb_season_stats[bad_metric])) / (max(qb_season_stats[bad_metric]) - min(qb_season_stats[bad_metric])))

In [415]:
norm_cols = [col for col in qb_season_stats.columns if col.endswith("_norm")]
qb_season_stats[norm_cols]

,first_down_rate_norm,completion_rate_norm,td_per_attempt_norm,epa_per_dropback_norm,yards_per_attempt_norm,int_rate_norm,fumble_lost_rate_norm,sack_rate_norm,sack_yards_per_sack_norm
1,0.238881,0.156022,0.777439,0.527193,0.589021,0.099811,0.721024,1.000000,0.535476
2,0.589790,0.346813,0.457044,0.682600,0.514578,0.657963,1.000000,0.875625,0.450024
8,0.293747,0.671043,0.798329,0.483738,0.337000,0.757127,0.398955,0.600114,0.127749
9,0.613717,0.923193,0.671350,0.705331,0.487024,0.813241,0.278746,0.895105,0.343748
10,0.388441,0.531974,0.015716,0.396884,0.374813,0.370552,1.000000,0.371812,0.553787
12,0.480155,0.527522,0.384819,0.631547,0.431372,0.752842,0.665229,0.845526,0.631166
14,0.474275,0.837531,0.448974,0.605720,0.386907,0.858831,0.693560,0.882368,0.508305
23,0.702067,0.926389,0.789799,0.826811,0.525073,0.838614,0.811946,0.819382,0.363633
24,0.677948,0.740544,0.580906,0.727417,0.503005,0.697384,0.627447,0.929232,0.371897
31,0.514708,0.731871,0.441821,0.656924,0.370176,0.585896,0.715659,0.958816,0.466301
33,0.315514,0.364401,0.371561,0.262212,0.105083,0.729380,0.164059,0.833765,0.619492
41,0.624993,0.732546,0.772574,0.715273,0.619298,0.836670,0.281666,0.723402,0.174203
42,0.444842,0.492469,0.550866,0.657771,0.403229,0.764195,0.707214,0.789585,0.147281
43,0.516681,0.675315,1.000000,0.765271,0.473098,0.350409,0.607676,0.984629,0.303535
46,0.718609,1.000000,0.741208,0.665839,0.599907,0.420755,1.000000,0.611842,0.511061
47,0.444485,0.606439,0.501351,0.441524,0.299845,0.733705,1.000000,0.812431,0.384918
50,0.270732,0.319418,0.287768,0.511854,0.307550,0.742628,0.435660,0.797929,0.059387
54,0.802526,0.909150,0.560826,0.849183,0.669294,0.538123,0.497938,0.914406,0.175568
55,0.600847,0.487255,0.749331,0.753691,0.412366,0.723174,0.708656,0.914219,0.811363
56,0.427471,0.561203,0.536386,0.619816,0.338147,0.835634,0.878056,0.835826,0.801934
57,0.508251,0.585990,0.902738,0.698505,0.409479,0.449292,0.484818,0.814063,0.254706
58,0.367157,0.705079,0.366889,0.555336,0.207353,0.802104,0.847962,0.821663,0.645343
61,0.417073,0.244575,0.601978,0.389233,0.350471,0.558956,0.428571,0.489835,0.345706
62,0.364816,0.600676,0.425495,0.531056,0.397414,0.543590,0.308848,0.845971,0.323067
63,0.215801,0.544113,0.147181,0.301802,0.164032,0.236496,0.677696,0.834697,0.139290
64,0.176564,0.135939,0.015716,0.154994,0.170315,0.722451,0.000000,0.453879,0.613497
65,0.238881,0.416058,0.392067,0.295782,0.236461,0.250953,0.825280,0.566261,0.471810
66,1.000000,0.916157,0.969725,1.000000,1.000000,0.545067,0.749395,0.839337,0.048924
67,0.183830,0.302007,0.013281,0.348519,0.222390,0.928294,1.000000,0.787532,0.651712
68,0.000000,0.123485,0.220355,0.000000,0.129364,0.000000,0.750452,0.495752,0.686360
69,0.558210,0.481103,0.416210,0.412783,0.442556,0.355350,0.011933,0.730198,0.309836
73,0.045629,0.470188,0.538621,0.178120,0.173712,0.789291,0.724917,0.000000,0.000000
74,0.335455,0.307208,0.308925,0.456568,0.240948,0.679703,0.677696,0.794136,0.559891
78,0.033392,0.112315,0.000000,0.115001,0.000000,0.723882,0.397526,0.497405,0.702048
79,0.366284,0.000000,0.261633,0.461420,0.390149,0.825293,0.164059,0.544467,0.383756
80,0.686324,0.460381,0.566604,0.708886,0.663390,1.000000,0.559457,0.754180,1.000000

In [416]:
qb_season_stats[norm_cols].shape

(36, 9)

In [417]:
qb_season_stats[norm_cols].describe()

,first_down_rate_norm,completion_rate_norm,td_per_attempt_norm,epa_per_dropback_norm,yards_per_attempt_norm,int_rate_norm,fumble_lost_rate_norm,sack_rate_norm,sack_yards_per_sack_norm
count,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,0.434392,0.526288,0.488486,0.530406,0.387356,0.625490,0.605614,0.740705,0.429910
std,0.222323,0.259874,0.267745,0.225544,0.193203,0.236229,0.278233,0.205606,0.237005
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.287993,0.339964,0.352398,0.394971,0.239826,0.515915,0.421167,0.608910,0.291328
50%,0.435978,0.529748,0.479198,0.543196,0.388528,0.722812,0.677696,0.813247,0.417471
75%,0.592554,0.711777,0.688814,0.700212,0.491019,0.792494,0.765826,0.853385,0.614996
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [418]:
qb_season_stats.columns

Index(['player_id', 'player_name', 'player_display_name', 'headshot_url',
       'season', 'team', 'total_passing_yds', 'total_passing_tds',
       'total_rushing_tds', 'total_attempts', 'total_completions',
       'total_carries', 'total_ints', 'total_sack_fumbles',
       'total_sack_fumbles_lost', 'total_rushing_fumbles',
       'total_rushing_fumbles_lost', 'total_sacks', 'total_sack_yds_lost',
       'total_air_yds', 'total_epa', 'total_first_downs',
       'total_2pt_passing_convs', 'total_2pt_rushing_convs',
       'total_fantasy_points', 'total_dropbacks', 'total_fumbles_lost',
       'total_tds', 'int_rate', 'fumble_lost_rate', 'first_down_rate',
       'completion_rate', 'sack_rate', 'sack_yards_per_sack', 'td_per_attempt',
       'epa_per_dropback', 'yards_per_attempt', 'first_down_rate_norm',
       'completion_rate_norm', 'td_per_attempt_norm', 'epa_per_dropback_norm',
       'yards_per_attempt_norm', 'int_rate_norm', 'fumble_lost_rate_norm',
       'sack_rate_norm', 'sack_yards_per_sack_norm'],
      dtype='object')

In [419]:
qb_normalized_season_stats = qb_season_stats[['player_id','player_display_name', 'season','team', 'first_down_rate_norm',	'completion_rate_norm', 'td_per_attempt_norm', 'epa_per_dropback_norm',	'yards_per_attempt_norm', 'int_rate_norm', 'fumble_lost_rate_norm',	'sack_rate_norm', 'sack_yards_per_sack_norm']]

In [420]:
qb_normalized_season_stats

,player_id,player_display_name,season,team,first_down_rate_norm,completion_rate_norm,td_per_attempt_norm,epa_per_dropback_norm,yards_per_attempt_norm,int_rate_norm,fumble_lost_rate_norm,sack_rate_norm,sack_yards_per_sack_norm
1,00-0026158,Joe Flacco,2023,CLE,0.238881,0.156022,0.777439,0.527193,0.589021,0.099811,0.721024,1.000000,0.535476
2,00-0026498,Matthew Stafford,2023,LA,0.589790,0.346813,0.457044,0.682600,0.514578,0.657963,1.000000,0.875625,0.450024
8,00-0029263,Russell Wilson,2023,DEN,0.293747,0.671043,0.798329,0.483738,0.337000,0.757127,0.398955,0.600114,0.127749
9,00-0029604,Kirk Cousins,2023,MIN,0.613717,0.923193,0.671350,0.705331,0.487024,0.813241,0.278746,0.895105,0.343748
10,00-0029701,Ryan Tannehill,2023,TEN,0.388441,0.531974,0.015716,0.396884,0.374813,0.370552,1.000000,0.371812,0.553787
12,00-0030565,Geno Smith,2023,SEA,0.480155,0.527522,0.384819,0.631547,0.431372,0.752842,0.665229,0.845526,0.631166
14,00-0031280,Derek Carr,2023,NO,0.474275,0.837531,0.448974,0.605720,0.386907,0.858831,0.693560,0.882368,0.508305
23,00-0033077,Dak Prescott,2023,DAL,0.702067,0.926389,0.789799,0.826811,0.525073,0.838614,0.811946,0.819382,0.363633
24,00-0033106,Jared Goff,2023,DET,0.677948,0.740544,0.580906,0.727417,0.503005,0.697384,0.627447,0.929232,0.371897
31,00-0033873,Patrick Mahomes,2023,KC,0.514708,0.731871,0.441821,0.656924,0.370176,0.585896,0.715659,0.958816,0.466301
33,00-0033949,Joshua Dobbs,2023,ARI,0.315514,0.364401,0.371561,0.262212,0.105083,0.729380,0.164059,0.833765,0.619492
41,00-0034796,Lamar Jackson,2023,BAL,0.624993,0.732546,0.772574,0.715273,0.619298,0.836670,0.281666,0.723402,0.174203
42,00-0034855,Baker Mayfield,2023,TB,0.444842,0.492469,0.550866,0.657771,0.403229,0.764195,0.707214,0.789585,0.147281
43,00-0034857,Josh Allen,2023,BUF,0.516681,0.675315,1.000000,0.765271,0.473098,0.350409,0.607676,0.984629,0.303535
46,00-0035100,Jake Browning,2023,CIN,0.718609,1.000000,0.741208,0.665839,0.599907,0.420755,1.000000,0.611842,0.511061
47,00-0035228,Kyler Murray,2023,ARI,0.444485,0.606439,0.501351,0.441524,0.299845,0.733705,1.000000,0.812431,0.384918
50,00-0035289,Gardner Minshew,2023,IND,0.270732,0.319418,0.287768,0.511854,0.307550,0.742628,0.435660,0.797929,0.059387
54,00-0036212,Tua Tagovailoa,2023,MIA,0.802526,0.909150,0.560826,0.849183,0.669294,0.538123,0.497938,0.914406,0.175568
55,00-0036264,Jordan Love,2023,GB,0.600847,0.487255,0.749331,0.753691,0.412366,0.723174,0.708656,0.914219,0.811363
56,00-0036355,Justin Herbert,2023,LAC,0.427471,0.561203,0.536386,0.619816,0.338147,0.835634,0.878056,0.835826,0.801934
57,00-0036389,Jalen Hurts,2023,PHI,0.508251,0.585990,0.902738,0.698505,0.409479,0.449292,0.484818,0.814063,0.254706
58,00-0036442,Joe Burrow,2023,CIN,0.367157,0.705079,0.366889,0.555336,0.207353,0.802104,0.847962,0.821663,0.645343
61,00-0036945,Justin Fields,2023,CHI,0.417073,0.244575,0.601978,0.389233,0.350471,0.558956,0.428571,0.489835,0.345706
62,00-0036971,Trevor Lawrence,2023,JAX,0.364816,0.600676,0.425495,0.531056,0.397414,0.543590,0.308848,0.845971,0.323067
63,00-0036972,Mac Jones,2023,NE,0.215801,0.544113,0.147181,0.301802,0.164032,0.236496,0.677696,0.834697,0.139290
64,00-0037013,Zach Wilson,2023,NYJ,0.176564,0.135939,0.015716,0.154994,0.170315,0.722451,0.000000,0.453879,0.613497
65,00-0037077,Sam Howell,2023,WAS,0.238881,0.416058,0.392067,0.295782,0.236461,0.250953,0.825280,0.566261,0.471810
66,00-0037834,Brock Purdy,2023,SF,1.000000,0.916157,0.969725,1.000000,1.000000,0.545067,0.749395,0.839337,0.048924
67,00-0038102,Kenny Pickett,2023,PIT,0.183830,0.302007,0.013281,0.348519,0.222390,0.928294,1.000000,0.787532,0.651712
68,00-0038108,Bailey Zappe,2023,NE,0.000000,0.123485,0.220355,0.000000,0.129364,0.000000,0.750452,0.495752,0.686360
69,00-0038122,Desmond Ridder,2023,ATL,0.558210,0.481103,0.416210,0.412783,0.442556,0.355350,0.011933,0.730198,0.309836
73,00-0038476,Tommy DeVito,2023,NYG,0.045629,0.470188,0.538621,0.178120,0.173712,0.789291,0.724917,0.000000,0.000000
74,00-0038579,Aidan O'Connell,2023,LV,0.335455,0.307208,0.308925,0.456568,0.240948,0.679703,0.677696,0.794136,0.559891
78,00-0039150,Bryce Young,2023,CAR,0.033392,0.112315,0.000000,0.115001,0.000000,0.723882,0.397526,0.497405,0.702048
79,00-0039152,Will Levis,2023,TEN,0.366284,0.000000,0.261633,0.461420,0.390149,0.825293,0.164059,0.544467,0.383756
80,00-0039163,C.J. Stroud,2023,HOU,0.686324,0.460381,0.566604,0.708886,0.663390,1.000000,0.559457,0.754180,1.000000

In [421]:
qb_normalized_season_stats.describe()

,season,first_down_rate_norm,completion_rate_norm,td_per_attempt_norm,epa_per_dropback_norm,yards_per_attempt_norm,int_rate_norm,fumble_lost_rate_norm,sack_rate_norm,sack_yards_per_sack_norm
count,36.0,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000,36.000000
mean,2023.0,0.434392,0.526288,0.488486,0.530406,0.387356,0.625490,0.605614,0.740705,0.429910
std,0.0,0.222323,0.259874,0.267745,0.225544,0.193203,0.236229,0.278233,0.205606,0.237005
min,2023.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2023.0,0.287993,0.339964,0.352398,0.394971,0.239826,0.515915,0.421167,0.608910,0.291328
50%,2023.0,0.435978,0.529748,0.479198,0.543196,0.388528,0.722812,0.677696,0.813247,0.417471
75%,2023.0,0.592554,0.711777,0.688814,0.700212,0.491019,0.792494,0.765826,0.853385,0.614996
max,2023.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [422]:
#Calculation of cortisol scores for each qb 
rows = []
turnover_factors = ["int_rate_norm", "fumble_lost_rate_norm", "sack_rate_norm", "sack_yards_per_sack_norm"]
drive_factors = ["first_down_rate_norm", "completion_rate_norm"]
success_factors = ["td_per_attempt_norm", "epa_per_dropback_norm", "yards_per_attempt_norm"]

#Compute score values & averaging all three metrics to ensure turnovers don't dominate the final cortisol score
qb_normalized_season_stats["turnover_score"] = qb_normalized_season_stats[turnover_factors].mean(axis=1)
qb_normalized_season_stats["drive_score"] = qb_normalized_season_stats[drive_factors].mean(axis=1)
qb_normalized_season_stats["success_score"] = qb_normalized_season_stats[success_factors].mean(axis=1)

#Compute final cortisol values
qb_normalized_season_stats["cortisol_score"] = (
    0.4 * qb_normalized_season_stats["turnover_score"] +
    0.3 * qb_normalized_season_stats["drive_score"] +
    0.3 * qb_normalized_season_stats["success_score"]
)

#Create rank column based on final cortisol score from highest (most stable) to least stable qbs
qb_normalized_season_stats["rank"] = qb_normalized_season_stats["cortisol_score"].rank(
    ascending=False,
    method="min"
)

#create new dataframe from the newly created values
qb_cortisol_scores = qb_normalized_season_stats[
    [
        "player_id",
        "player_display_name",
        "team",
        "season",
        "turnover_score",
        "drive_score",
        "success_score",
        "cortisol_score",
        "rank"
    ]
].copy()

#sorting
qb_cortisol_scores = qb_cortisol_scores.sort_values(
    by="cortisol_score",
    ascending=False
)


#Change scoring range from 0-100 for better understanding
qb_cortisol_scores['cortisol_score'] = 100 * (qb_cortisol_scores['cortisol_score'] - qb_cortisol_scores['cortisol_score'].min()) / (qb_cortisol_scores['cortisol_score'].max() - qb_cortisol_scores['cortisol_score'].min())
qb_cortisol_scores['cortisol_score'] = qb_cortisol_scores['cortisol_score'].round(1)

qb_cortisol_scores = qb_cortisol_scores.rename(columns={'player_display_name':'qb_name'})

qb_cortisol_scores

/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/2573392917.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_normalized_season_stats["turnover_score"] = qb_normalized_season_stats[turnover_factors].mean(axis=1)
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/2573392917.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_normalized_season_stats["drive_score"] = qb_normalized_season_stats[drive_factors].mean(axis=1)
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/2573392917.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_normalized_season_stats["success_score"] = qb_normalized_season_stats[success_factors].mean(axis=1)
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/2573392917.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_normalized_season_stats["cortisol_score"] = (
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/2573392917.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  qb_normalized_season_stats["rank"] = qb_normalized_season_stats["cortisol_score"].rank(

,player_id,qb_name,team,season,turnover_score,drive_score,success_score,cortisol_score,rank
66,00-0037834,Brock Purdy,SF,2023,0.545681,0.958079,0.989908,100.0,1.0
23,00-0033077,Dak Prescott,DAL,2023,0.708394,0.814228,0.713894,89.0,2.0
46,00-0035100,Jake Browning,CIN,2023,0.635915,0.859304,0.668985,83.8,3.0
80,00-0039163,C.J. Stroud,HOU,2023,0.828409,0.573352,0.646294,81.0,4.0
54,00-0036212,Tua Tagovailoa,MIA,2023,0.531509,0.855838,0.693101,77.4,5.0
55,00-0036264,Jordan Love,GB,2023,0.789353,0.544051,0.638463,76.2,6.0
24,00-0033106,Jared Goff,DET,2023,0.656490,0.709246,0.603776,73.7,7.0
9,00-0029604,Kirk Cousins,MIN,2023,0.582710,0.768455,0.621235,72.5,8.0
14,00-0031280,Derek Carr,NO,2023,0.735766,0.655903,0.480534,69.9,9.0
56,00-0036355,Justin Herbert,LAC,2023,0.837863,0.494337,0.498117,69.5,10.0
43,00-0034857,Josh Allen,BUF,2023,0.561562,0.595998,0.746123,68.4,11.0
41,00-0034796,Lamar Jackson,BAL,2023,0.503985,0.678770,0.702382,66.4,12.0
31,00-0033873,Patrick Mahomes,KC,2023,0.681668,0.623289,0.489640,64.7,13.0
2,00-0026498,Matthew Stafford,LA,2023,0.745903,0.468302,0.551407,64.3,14.0
58,00-0036442,Joe Burrow,CIN,2023,0.779268,0.536118,0.376526,60.9,15.0
12,00-0030565,Geno Smith,SEA,2023,0.723691,0.503839,0.482579,60.9,16.0
47,00-0035228,Kyler Murray,ARI,2023,0.732764,0.525462,0.414240,59.0,17.0
57,00-0036389,Jalen Hurts,PHI,2023,0.500720,0.547121,0.670241,57.3,18.0
42,00-0034855,Baker Mayfield,TB,2023,0.602069,0.468655,0.537289,53.2,19.0
8,00-0029263,Russell Wilson,DEN,2023,0.470986,0.482395,0.539689,44.7,20.0
1,00-0026158,Joe Flacco,CLE,2023,0.589078,0.197451,0.631218,42.7,21.0
62,00-0036971,Trevor Lawrence,JAX,2023,0.505369,0.482746,0.451322,42.4,22.0
74,00-0038579,Aidan O'Connell,LV,2023,0.677857,0.321331,0.335480,39.8,23.0
67,00-0038102,Kenny Pickett,PIT,2023,0.841884,0.242919,0.194730,39.8,24.0
10,00-0029701,Ryan Tannehill,TEN,2023,0.574038,0.460208,0.262471,35.9,25.0
69,00-0038122,Desmond Ridder,ATL,2023,0.351829,0.519656,0.423849,31.8,26.0
61,00-0036945,Justin Fields,CHI,2023,0.455767,0.330824,0.447227,30.4,27.0
33,00-0033949,Joshua Dobbs,ARI,2023,0.586674,0.339958,0.246285,29.5,28.0
50,00-0035289,Gardner Minshew,IND,2023,0.508901,0.295075,0.369057,28.1,29.0
65,00-0037077,Sam Howell,WAS,2023,0.528576,0.327470,0.308103,27.9,30.0
63,00-0036972,Mac Jones,NE,2023,0.472045,0.379957,0.204338,21.1,31.0
79,00-0039152,Will Levis,TEN,2023,0.479394,0.183142,0.371067,20.0,32.0
73,00-0038476,Tommy DeVito,NYG,2023,0.378552,0.257908,0.296818,12.8,33.0
78,00-0039150,Bryce Young,CAR,2023,0.580215,0.072853,0.038334,3.4,34.0
64,00-0037013,Zach Wilson,NYJ,2023,0.447457,0.156252,0.113675,2.4,35.0
68,00-0038108,Bailey Zappe,NE,2023,0.483141,0.061743,0.116573,0.0,36.0

In [423]:
qb_cortisol_scores.describe()

,season,turnover_score,drive_score,success_score,cortisol_score,rank
count,36.0,36.000000,36.000000,36.000000,36.000000,36.000000
mean,2023.0,0.600430,0.480340,0.468749,50.022222,18.500000
std,0.0,0.131474,0.223266,0.208390,25.924143,10.535654
min,2023.0,0.351829,0.061743,0.038334,0.000000,1.000000
25%,2023.0,0.503169,0.325935,0.328636,30.175000,9.750000
50%,2023.0,0.581462,0.488541,0.481557,55.250000,18.500000
75%,2023.0,0.712218,0.602821,0.633029,69.600000,27.250000
max,2023.0,0.841884,0.958079,0.989908,100.000000,36.000000

In [424]:
qb_cortisol_scores[[
    "turnover_score",
    "drive_score",
    "success_score",
    "cortisol_score"
]].corr()

                turnover_score  drive_score  success_score  cortisol_score
turnover_score        1.000000     0.237856       0.166663        0.547579
drive_score           0.237856     1.000000       0.818810        0.906281
success_score         0.166663     0.818810       1.000000        0.874723
cortisol_score        0.547579     0.906281       0.874723        1.000000

In [425]:
qb_cortisol_scores

,player_id,qb_name,team,season,turnover_score,drive_score,success_score,cortisol_score,rank
66,00-0037834,Brock Purdy,SF,2023,0.545681,0.958079,0.989908,100.0,1.0
23,00-0033077,Dak Prescott,DAL,2023,0.708394,0.814228,0.713894,89.0,2.0
46,00-0035100,Jake Browning,CIN,2023,0.635915,0.859304,0.668985,83.8,3.0
80,00-0039163,C.J. Stroud,HOU,2023,0.828409,0.573352,0.646294,81.0,4.0
54,00-0036212,Tua Tagovailoa,MIA,2023,0.531509,0.855838,0.693101,77.4,5.0
55,00-0036264,Jordan Love,GB,2023,0.789353,0.544051,0.638463,76.2,6.0
24,00-0033106,Jared Goff,DET,2023,0.656490,0.709246,0.603776,73.7,7.0
9,00-0029604,Kirk Cousins,MIN,2023,0.582710,0.768455,0.621235,72.5,8.0
14,00-0031280,Derek Carr,NO,2023,0.735766,0.655903,0.480534,69.9,9.0
56,00-0036355,Justin Herbert,LAC,2023,0.837863,0.494337,0.498117,69.5,10.0
43,00-0034857,Josh Allen,BUF,2023,0.561562,0.595998,0.746123,68.4,11.0
41,00-0034796,Lamar Jackson,BAL,2023,0.503985,0.678770,0.702382,66.4,12.0
31,00-0033873,Patrick Mahomes,KC,2023,0.681668,0.623289,0.489640,64.7,13.0
2,00-0026498,Matthew Stafford,LA,2023,0.745903,0.468302,0.551407,64.3,14.0
58,00-0036442,Joe Burrow,CIN,2023,0.779268,0.536118,0.376526,60.9,15.0
12,00-0030565,Geno Smith,SEA,2023,0.723691,0.503839,0.482579,60.9,16.0
47,00-0035228,Kyler Murray,ARI,2023,0.732764,0.525462,0.414240,59.0,17.0
57,00-0036389,Jalen Hurts,PHI,2023,0.500720,0.547121,0.670241,57.3,18.0
42,00-0034855,Baker Mayfield,TB,2023,0.602069,0.468655,0.537289,53.2,19.0
8,00-0029263,Russell Wilson,DEN,2023,0.470986,0.482395,0.539689,44.7,20.0
1,00-0026158,Joe Flacco,CLE,2023,0.589078,0.197451,0.631218,42.7,21.0
62,00-0036971,Trevor Lawrence,JAX,2023,0.505369,0.482746,0.451322,42.4,22.0
74,00-0038579,Aidan O'Connell,LV,2023,0.677857,0.321331,0.335480,39.8,23.0
67,00-0038102,Kenny Pickett,PIT,2023,0.841884,0.242919,0.194730,39.8,24.0
10,00-0029701,Ryan Tannehill,TEN,2023,0.574038,0.460208,0.262471,35.9,25.0
69,00-0038122,Desmond Ridder,ATL,2023,0.351829,0.519656,0.423849,31.8,26.0
61,00-0036945,Justin Fields,CHI,2023,0.455767,0.330824,0.447227,30.4,27.0
33,00-0033949,Joshua Dobbs,ARI,2023,0.586674,0.339958,0.246285,29.5,28.0
50,00-0035289,Gardner Minshew,IND,2023,0.508901,0.295075,0.369057,28.1,29.0
65,00-0037077,Sam Howell,WAS,2023,0.528576,0.327470,0.308103,27.9,30.0
63,00-0036972,Mac Jones,NE,2023,0.472045,0.379957,0.204338,21.1,31.0
79,00-0039152,Will Levis,TEN,2023,0.479394,0.183142,0.371067,20.0,32.0
73,00-0038476,Tommy DeVito,NYG,2023,0.378552,0.257908,0.296818,12.8,33.0
78,00-0039150,Bryce Young,CAR,2023,0.580215,0.072853,0.038334,3.4,34.0
64,00-0037013,Zach Wilson,NYJ,2023,0.447457,0.156252,0.113675,2.4,35.0
68,00-0038108,Bailey Zappe,NE,2023,0.483141,0.061743,0.116573,0.0,36.0

In [426]:
#Jake Browning, a backup QB that played 10 games in the 2023 season and recorded 267 dropbacks, relatively low compared to the other QBs yet he still ranked #3 in terms of cortisol score
#adjustment below aims to move outliers like Browning closer to the league average 

avg_cortisol_score = qb_cortisol_scores['cortisol_score'].mean()
K = 400

qb_cortisol_scores['total_dropbacks'] = qb_season_stats['total_dropbacks']
qb_cortisol_scores['stabilized_cortisol_score'] = (
    (qb_cortisol_scores["total_dropbacks"] /
    (qb_cortisol_scores["total_dropbacks"] + K)) *
    qb_cortisol_scores["cortisol_score"]
) + (
    (K /
    (qb_cortisol_scores["total_dropbacks"] + K)) *
    avg_cortisol_score
)

qb_cortisol_scores = qb_cortisol_scores.sort_values(
    by="stabilized_cortisol_score",
    ascending=False
)

qb_cortisol_scores["stabilized_rank"] = range(1, len(qb_cortisol_scores)+1)

In [427]:
qb_cortisol_scores

,player_id,qb_name,team,season,turnover_score,drive_score,success_score,cortisol_score,rank,total_dropbacks,stabilized_cortisol_score,stabilized_rank
66,00-0037834,Brock Purdy,SF,2023,0.545681,0.958079,0.989908,100.0,1.0,472,77.074414,1
23,00-0033077,Dak Prescott,DAL,2023,0.708394,0.814228,0.713894,89.0,2.0,629,73.848289,2
80,00-0039163,C.J. Stroud,HOU,2023,0.828409,0.573352,0.646294,81.0,4.0,537,67.775762,3
54,00-0036212,Tua Tagovailoa,MIA,2023,0.531509,0.855838,0.693101,77.4,5.0,589,66.327087,4
55,00-0036264,Jordan Love,GB,2023,0.789353,0.544051,0.638463,76.2,6.0,609,65.822288,5
24,00-0033106,Jared Goff,DET,2023,0.656490,0.709246,0.603776,73.7,7.0,635,64.549168,6
46,00-0035100,Jake Browning,CIN,2023,0.635915,0.859304,0.668985,83.8,3.0,267,63.543462,7
14,00-0031280,Derek Carr,NO,2023,0.735766,0.655903,0.480534,69.9,9.0,579,61.778334,8
43,00-0034857,Josh Allen,BUF,2023,0.561562,0.595998,0.746123,68.4,11.0,603,61.070876,9
56,00-0036355,Justin Herbert,LAC,2023,0.837863,0.494337,0.498117,69.5,10.0,485,60.696485,10
9,00-0029604,Kirk Cousins,MIN,2023,0.582710,0.768455,0.621235,72.5,8.0,328,60.149573,11
41,00-0034796,Lamar Jackson,BAL,2023,0.503985,0.678770,0.702382,66.4,12.0,494,59.072135,12
31,00-0033873,Patrick Mahomes,KC,2023,0.681668,0.623289,0.489640,64.7,13.0,624,58.966493,13
2,00-0026498,Matthew Stafford,LA,2023,0.745903,0.468302,0.551407,64.3,14.0,551,58.294626,14
12,00-0030565,Geno Smith,SEA,2023,0.723691,0.503839,0.482579,60.9,16.0,530,56.221386,15
58,00-0036442,Joe Burrow,CIN,2023,0.779268,0.536118,0.376526,60.9,15.0,389,55.385284,16
57,00-0036389,Jalen Hurts,PHI,2023,0.500720,0.547121,0.670241,57.3,18.0,574,54.311180,17
47,00-0035228,Kyler Murray,ARI,2023,0.732764,0.525462,0.414240,59.0,17.0,286,53.765144,18
42,00-0034855,Baker Mayfield,TB,2023,0.602069,0.468655,0.537289,53.2,19.0,606,51.936470,19
1,00-0026158,Joe Flacco,CLE,2023,0.589078,0.197451,0.631218,42.7,21.0,212,47.485766,20
8,00-0029263,Russell Wilson,DEN,2023,0.470986,0.482395,0.539689,44.7,20.0,492,47.086647,21
62,00-0036971,Trevor Lawrence,JAX,2023,0.505369,0.482746,0.451322,42.4,22.0,599,45.451941,22
67,00-0038102,Kenny Pickett,PIT,2023,0.841884,0.242919,0.194730,39.8,24.0,347,45.273747,23
74,00-0038579,Aidan O'Connell,LV,2023,0.677857,0.321331,0.335480,39.8,23.0,367,45.131016,24
10,00-0029701,Ryan Tannehill,TEN,2023,0.574038,0.460208,0.262471,35.9,25.0,262,44.433065,25
33,00-0033949,Joshua Dobbs,ARI,2023,0.586674,0.339958,0.246285,29.5,28.0,283,41.518871,26
69,00-0038122,Desmond Ridder,ATL,2023,0.351829,0.519656,0.423849,31.8,26.0,419,40.699742,27
61,00-0036945,Justin Fields,CHI,2023,0.455767,0.330824,0.447227,30.4,27.0,414,40.042370,28
50,00-0035289,Gardner Minshew,IND,2023,0.508901,0.295075,0.369057,28.1,29.0,524,37.590139,29
79,00-0039152,Will Levis,TEN,2023,0.479394,0.183142,0.371067,20.0,32.0,283,37.582561,30
73,00-0038476,Tommy DeVito,NYG,2023,0.378552,0.257908,0.296818,12.8,33.0,215,37.009575,31
63,00-0036972,Mac Jones,NE,2023,0.472045,0.379957,0.204338,21.1,31.0,367,36.183297,32
65,00-0037077,Sam Howell,WAS,2023,0.528576,0.327470,0.308103,27.9,30.0,677,36.116239,33
68,00-0038108,Bailey Zappe,NE,2023,0.483141,0.061743,0.116573,0.0,36.0,237,31.411129,34
64,00-0037013,Zach Wilson,NYJ,2023,0.447457,0.156252,0.113675,2.4,35.0,414,25.801583,35
78,00-0039150,Bryce Young,CAR,2023,0.580215,0.072853,0.038334,3.4,34.0,589,22.256308,36

In [428]:
qb_cortisol_scores.shape

(36, 12)

In [429]:
qb_cortisol_scores = qb_cortisol_scores[['player_id', 'qb_name', 'season',
'team',
'turnover_score',
'drive_score',
'success_score',
'cortisol_score',
'rank',
'total_dropbacks',
'stabilized_cortisol_score', 'stabilized_rank']]

In [430]:
qb_cortisol_scores

,player_id,qb_name,season,team,turnover_score,drive_score,success_score,cortisol_score,rank,total_dropbacks,stabilized_cortisol_score,stabilized_rank
66,00-0037834,Brock Purdy,2023,SF,0.545681,0.958079,0.989908,100.0,1.0,472,77.074414,1
23,00-0033077,Dak Prescott,2023,DAL,0.708394,0.814228,0.713894,89.0,2.0,629,73.848289,2
80,00-0039163,C.J. Stroud,2023,HOU,0.828409,0.573352,0.646294,81.0,4.0,537,67.775762,3
54,00-0036212,Tua Tagovailoa,2023,MIA,0.531509,0.855838,0.693101,77.4,5.0,589,66.327087,4
55,00-0036264,Jordan Love,2023,GB,0.789353,0.544051,0.638463,76.2,6.0,609,65.822288,5
24,00-0033106,Jared Goff,2023,DET,0.656490,0.709246,0.603776,73.7,7.0,635,64.549168,6
46,00-0035100,Jake Browning,2023,CIN,0.635915,0.859304,0.668985,83.8,3.0,267,63.543462,7
14,00-0031280,Derek Carr,2023,NO,0.735766,0.655903,0.480534,69.9,9.0,579,61.778334,8
43,00-0034857,Josh Allen,2023,BUF,0.561562,0.595998,0.746123,68.4,11.0,603,61.070876,9
56,00-0036355,Justin Herbert,2023,LAC,0.837863,0.494337,0.498117,69.5,10.0,485,60.696485,10
9,00-0029604,Kirk Cousins,2023,MIN,0.582710,0.768455,0.621235,72.5,8.0,328,60.149573,11
41,00-0034796,Lamar Jackson,2023,BAL,0.503985,0.678770,0.702382,66.4,12.0,494,59.072135,12
31,00-0033873,Patrick Mahomes,2023,KC,0.681668,0.623289,0.489640,64.7,13.0,624,58.966493,13
2,00-0026498,Matthew Stafford,2023,LA,0.745903,0.468302,0.551407,64.3,14.0,551,58.294626,14
12,00-0030565,Geno Smith,2023,SEA,0.723691,0.503839,0.482579,60.9,16.0,530,56.221386,15
58,00-0036442,Joe Burrow,2023,CIN,0.779268,0.536118,0.376526,60.9,15.0,389,55.385284,16
57,00-0036389,Jalen Hurts,2023,PHI,0.500720,0.547121,0.670241,57.3,18.0,574,54.311180,17
47,00-0035228,Kyler Murray,2023,ARI,0.732764,0.525462,0.414240,59.0,17.0,286,53.765144,18
42,00-0034855,Baker Mayfield,2023,TB,0.602069,0.468655,0.537289,53.2,19.0,606,51.936470,19
1,00-0026158,Joe Flacco,2023,CLE,0.589078,0.197451,0.631218,42.7,21.0,212,47.485766,20
8,00-0029263,Russell Wilson,2023,DEN,0.470986,0.482395,0.539689,44.7,20.0,492,47.086647,21
62,00-0036971,Trevor Lawrence,2023,JAX,0.505369,0.482746,0.451322,42.4,22.0,599,45.451941,22
67,00-0038102,Kenny Pickett,2023,PIT,0.841884,0.242919,0.194730,39.8,24.0,347,45.273747,23
74,00-0038579,Aidan O'Connell,2023,LV,0.677857,0.321331,0.335480,39.8,23.0,367,45.131016,24
10,00-0029701,Ryan Tannehill,2023,TEN,0.574038,0.460208,0.262471,35.9,25.0,262,44.433065,25
33,00-0033949,Joshua Dobbs,2023,ARI,0.586674,0.339958,0.246285,29.5,28.0,283,41.518871,26
69,00-0038122,Desmond Ridder,2023,ATL,0.351829,0.519656,0.423849,31.8,26.0,419,40.699742,27
61,00-0036945,Justin Fields,2023,CHI,0.455767,0.330824,0.447227,30.4,27.0,414,40.042370,28
50,00-0035289,Gardner Minshew,2023,IND,0.508901,0.295075,0.369057,28.1,29.0,524,37.590139,29
79,00-0039152,Will Levis,2023,TEN,0.479394,0.183142,0.371067,20.0,32.0,283,37.582561,30
73,00-0038476,Tommy DeVito,2023,NYG,0.378552,0.257908,0.296818,12.8,33.0,215,37.009575,31
63,00-0036972,Mac Jones,2023,NE,0.472045,0.379957,0.204338,21.1,31.0,367,36.183297,32
65,00-0037077,Sam Howell,2023,WAS,0.528576,0.327470,0.308103,27.9,30.0,677,36.116239,33
68,00-0038108,Bailey Zappe,2023,NE,0.483141,0.061743,0.116573,0.0,36.0,237,31.411129,34
64,00-0037013,Zach Wilson,2023,NYJ,0.447457,0.156252,0.113675,2.4,35.0,414,25.801583,35
78,00-0039150,Bryce Young,2023,CAR,0.580215,0.072853,0.038334,3.4,34.0,589,22.256308,36

In [431]:
qb_cortisol_scores.to_csv("../data/processed/qb_cortisol_scores_2023.csv", index=False)

In [432]:
player_stats_23.columns

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'season', 'week', 'season_type',
       'game_id',
       ...
       'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att',
       'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'fantasy_points',
       'fantasy_points_ppr'],
      dtype='object', length=115)

In [433]:
#Phase 2 of this project involves implementing advanced metrics, such as negative EPA play rate, panic play rate, 3rd down conversion rate, 3rd and long conversion rate, & red-zone TD rate. This will require use of nflreadpy's play-by-play data.

In [434]:
pbp_2023 = nfl.load_pbp([2023])

In [435]:
pbp_2023

shape: (49_665, 372)
┌─────────┬────────────┬────────────┬───────────┬───┬────────────┬──────────┬──────────┬───────────┐
│ play_id ┆ game_id    ┆ old_game_i ┆ home_team ┆ … ┆ xyac_succe ┆ xyac_fd  ┆ xpass    ┆ pass_oe   │
│ ---     ┆ ---        ┆ d          ┆ ---       ┆   ┆ ss         ┆ ---      ┆ ---      ┆ ---       │
│ f64     ┆ str        ┆ ---        ┆ str       ┆   ┆ ---        ┆ f64      ┆ f64      ┆ f64       │
│         ┆            ┆ str        ┆           ┆   ┆ f64        ┆          ┆          ┆           │
╞═════════╪════════════╪════════════╪═══════════╪═══╪════════════╪══════════╪══════════╪═══════════╡
│ 1.0     ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 39.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 55.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ 0.515058 ┆ -51.50584 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 6         │
│ 77.0    ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ 0.996628   ┆ 0.583928 ┆ 0.661106 ┆ 33.889407 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 102.0   ┆ 2023_01_AR ┆ 2023091007 ┆ WAS       ┆ … ┆ null       ┆ null     ┆ 0.196065 ┆ -19.60646 │
│         ┆ I_WAS      ┆            ┆           ┆   ┆            ┆          ┆          ┆ 7         │
│ …       ┆ …          ┆ …          ┆ …         ┆ … ┆ …          ┆ …        ┆ …        ┆ …         │
│ 4791.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ null       ┆ null     ┆ 0.182589 ┆ 81.741054 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 4813.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ null       ┆ null     ┆ 0.310144 ┆ -31.01439 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆ 8         │
│ 4835.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ 0.428395   ┆ 0.361828 ┆ 0.6004   ┆ 39.959973 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 4860.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ 0.993362   ┆ 0.784198 ┆ 0.623245 ┆ 37.675518 │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
│ 4881.0  ┆ 2023_22_SF ┆ 2024021100 ┆ KC        ┆ … ┆ null       ┆ null     ┆ null     ┆ null      │
│         ┆ _KC        ┆            ┆           ┆   ┆            ┆          ┆          ┆           │
└─────────┴────────────┴────────────┴───────────┴───┴────────────┴──────────┴──────────┴───────────┘

In [436]:
pbp_2023.columns

['play_id',
 'game_id',
 'old_game_id',
 'home_team',
 'away_team',
 'season_type',
 'week',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'td_player_name',
 'td_player_id',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'vegas_wpa',
 'vegas_home_wpa',
 'home_wp_post',
 'away_wp_post',
 'vegas_wp',
 'vegas_home_wp',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'touchback',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiver_player_name',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_receiving_yards',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_rushing_yards',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'tackle_with_assist',
 'tackle_with_assist_1_player_id',
 'tackle_with_assist_1_player_name',
 'tackle_with_assist_1_team',
 'tackle_with_assist_2_player_id',
 'tackle_with_assist_2_player_name',
 'tackle_with_assist_2_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'sack_player_id',
 'sack_player_name',
 'half_sack_1_player_id',
 'half_sack_1_player_name',
 'half_sack_2_player_id',
 'half_sack_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv',
 'safety_player_name',
 'safety_player_id',
 'season',
 'cp',
 'cpoe',
 'series',
 'series_success',
 'series_result',
 'order_sequence',
 'start_time',
 'time_of_day',
 'stadium',
 'weather',
 'nfl_api_id',
 'play_clock',
 'play_deleted',
 'play_type_nfl',
 'special_teams_play',
 'st_play_type',
 'end_clock_time',
 'end_yard_line',
 'fixed_drive',
 'fixed_drive_result',
 'drive_real_start_time',
 'drive_play_count',
 'drive_time_of_possession',
 'drive_first_downs',
 'drive_inside20',
 'drive_ended_with_score',
 'drive_quarter_start',
 'drive_quarter_end',
 'drive_yards_penalized',
 'drive_start_transition',
 'drive_end_transition',
 'drive_game_clock_start',
 'drive_game_clock_end',
 'drive_start_yard_line',
 'drive_end_yard_line',
 'drive_play_id_started',
 'drive_play_id_ended',
 'away_score',
 'home_score',
 'location',
 'result',
 'total',
 'spread_line',
 'total_line',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'home_coach',
 'away_coach',
 'stadium_id',
 'game_stadium',
 'aborted_play',
 'success',
 'passer',
 'passer_jersey_number',
 'rusher',
 'rusher_jersey_number',
 'receiver',
 'receiver_jersey_number',
 'pass',
 'rush',
 'first_down',
 'special',
 'play',
 'passer_id',
 'rusher_id',
 'receiver_id',
 'name',
 'jersey_number',
 'id',
 'fantasy_player_name',
 'fantasy_player_id',
 'fantasy',
 'fantasy_id',
 'out_of_bounds',
 'home_opening_kickoff',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass',
 'pass_oe']

In [437]:
pbp_2023['qb_epa']

shape: (49_665,)
Series: 'qb_epa' [f64]
[
	0.0
	0.0
	-0.336103
	0.703308
	0.469799
	…
	1.728891
	-0.330699
	-0.637115
	3.102806
	null
]

In [438]:
pbp_2023['passer_player_id']

shape: (49_665,)
Series: 'passer_player_id' [str]
[
	null
	null
	null
	"00-0037077"
	null
	…
	null
	null
	"00-0033873"
	"00-0033873"
	null
]

In [439]:
pbp_2023['play_type']

shape: (49_665,)
Series: 'play_type' [str]
[
	null
	"kickoff"
	"run"
	"pass"
	"run"
	…
	"run"
	"run"
	"pass"
	"pass"
	null
]

In [440]:
pbp_2023['play_type_nfl'].unique()

shape: (17,)
Series: 'play_type_nfl' [str]
[
	"INTERCEPTION"
	"FIELD_GOAL"
	"TIMEOUT"
	"PASS"
	"COMMENT"
	…
	"RUSH"
	"END_GAME"
	"PUNT"
	"UNSPECIFIED"
	"PAT2"
]

In [441]:
type(pbp_2023)

polars.dataframe.frame.DataFrame

In [442]:
pbp_2023 = pbp_2023.to_pandas()

In [443]:
type(pbp_2023)

pandas.core.frame.DataFrame

In [444]:
pbp_2023

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2023_01_ARI_WAS,2023091007,WAS,ARI,REG,1,None,None,None,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39.0,2023_01_ARI_WAS,2023091007,WAS,ARI,REG,1,WAS,home,ARI,...,0.0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,55.0,2023_01_ARI_WAS,2023091007,WAS,ARI,REG,1,WAS,home,ARI,...,0.0,1.0,-0.336103,NaN,NaN,NaN,NaN,NaN,0.515058,-51.505846
3,77.0,2023_01_ARI_WAS,2023091007,WAS,ARI,REG,1,WAS,home,ARI,...,0.0,1.0,0.703308,0.340652,3.328642,1.0,0.996628,0.583928,0.661106,33.889407
4,102.0,2023_01_ARI_WAS,2023091007,WAS,ARI,REG,1,WAS,home,ARI,...,0.0,1.0,0.469799,NaN,NaN,NaN,NaN,NaN,0.196065,-19.606467
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49660,4791.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,1.728891,NaN,NaN,NaN,NaN,NaN,0.182589,81.741054
49661,4813.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,-0.330699,NaN,NaN,NaN,NaN,NaN,0.310144,-31.014398
49662,4835.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,-0.637115,1.315985,6.498790,6.0,0.428395,0.361828,0.600400,39.959973
49663,4860.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,3.102806,1.780787,0.772520,1.0,0.993362,0.784198,0.623245,37.675518
49664,4881.0,2023_22_SF_KC,2024021100,KC,SF,POST,22,KC,home,SF,...,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [445]:
#Check which id to use as primary key for joining later by calculating the total missing values for each column
print(pbp_2023['passer_player_id'].isna().sum())
print(pbp_2023['id'].isna().sum())
print(pbp_2023['passer_id'].isna().sum())

28868
12162
26686

In [446]:
#Filter df by QB's only based on dropbacks (qb_dropback of 1 indicates either a pass, fumble, or sack)
pbp_2023 = pbp_2023[(pbp_2023['season_type']=="REG") & (pbp_2023['qb_dropback']==1)]
print(pbp_2023['passer_player_id'].isna().sum())
print(pbp_2023['id'].isna().sum())
print(pbp_2023['passer_id'].isna().sum())
#Clearly, both id and passer_id are acceptable; however, passer_id is problematic for sacks and fumbles because those two don't count as passes
#therefore, id is a better option

1035
1
1

In [447]:
#Select subset of columns required for computing each advanced metric
pbp_2023 = pbp_2023.rename(columns={'id':'player_id'})
pbp_2023 = pbp_2023[['player_id', 'season', 'qb_epa', 'play_type','down', 'qb_dropback', 'third_down_converted', 'ydstogo', 'yardline_100', 'pass_touchdown']]

In [448]:
pbp_2023

,player_id,season,qb_epa,play_type,down,qb_dropback,third_down_converted,ydstogo,yardline_100,pass_touchdown
3,00-0037077,2023,0.703308,pass,2.0,1.0,0.0,7.0,72.0,0.0
5,00-0037077,2023,-0.521544,pass,1.0,1.0,0.0,10.0,64.0,0.0
6,00-0037077,2023,1.173155,pass,2.0,1.0,0.0,10.0,64.0,0.0
7,00-0037077,2023,-0.515452,pass,1.0,1.0,0.0,10.0,52.0,0.0
8,00-0037077,2023,-0.872005,pass,2.0,1.0,0.0,9.0,51.0,0.0
...,...,...,...,...,...,...,...,...,...,...
47375,00-0039150,2023,0.351918,pass,2.0,1.0,0.0,6.0,59.0,0.0
47378,00-0039150,2023,-0.230056,pass,1.0,1.0,0.0,10.0,52.0,0.0
47379,00-0039150,2023,1.611585,run,2.0,1.0,0.0,6.0,48.0,0.0
47381,00-0039150,2023,-5.466342,pass,1.0,1.0,0.0,15.0,33.0,0.0
47391,00-0034855,2023,1.995936,pass,3.0,1.0,1.0,5.0,36.0,0.0

In [449]:
#Helper columns for advanced metrics
pbp_2023['is_third_down'] = pbp_2023['down']==3
pbp_2023['is_third_and_long'] =  ((pbp_2023['down'] == 3) & (pbp_2023['ydstogo'] >= 7))
pbp_2023['is_third_and_long_conversion'] = (pbp_2023['is_third_and_long'] & (pbp_2023['third_down_converted']==1))
pbp_2023['is_third_down_conversion'] = (pbp_2023['is_third_down'] & (pbp_2023['third_down_converted']==1))
pbp_2023['is_negative_epa'] = pbp_2023['qb_epa'] < 0
pbp_2023['is_panic_play'] = ((pbp_2023['qb_epa'] < -1) & (pbp_2023['ydstogo'] >= 7) & (pbp_2023['down'].isin([3,4])))
pbp_2023['is_redzone'] = pbp_2023['yardline_100'] <= 20
pbp_2023['is_redzone_td'] = (pbp_2023['is_redzone'] & (pbp_2023['pass_touchdown']==1))

In [450]:
pbp_2023

,player_id,season,qb_epa,play_type,down,qb_dropback,third_down_converted,ydstogo,yardline_100,pass_touchdown,is_third_down,is_third_and_long,is_third_and_long_conversion,is_third_down_conversion,is_negative_epa,is_panic_play,is_redzone,is_redzone_td
3,00-0037077,2023,0.703308,pass,2.0,1.0,0.0,7.0,72.0,0.0,False,False,False,False,False,False,False,False
5,00-0037077,2023,-0.521544,pass,1.0,1.0,0.0,10.0,64.0,0.0,False,False,False,False,True,False,False,False
6,00-0037077,2023,1.173155,pass,2.0,1.0,0.0,10.0,64.0,0.0,False,False,False,False,False,False,False,False
7,00-0037077,2023,-0.515452,pass,1.0,1.0,0.0,10.0,52.0,0.0,False,False,False,False,True,False,False,False
8,00-0037077,2023,-0.872005,pass,2.0,1.0,0.0,9.0,51.0,0.0,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47375,00-0039150,2023,0.351918,pass,2.0,1.0,0.0,6.0,59.0,0.0,False,False,False,False,False,False,False,False
47378,00-0039150,2023,-0.230056,pass,1.0,1.0,0.0,10.0,52.0,0.0,False,False,False,False,True,False,False,False
47379,00-0039150,2023,1.611585,run,2.0,1.0,0.0,6.0,48.0,0.0,False,False,False,False,False,False,False,False
47381,00-0039150,2023,-5.466342,pass,1.0,1.0,0.0,15.0,33.0,0.0,False,False,False,False,True,False,False,False
47391,00-0034855,2023,1.995936,pass,3.0,1.0,1.0,5.0,36.0,0.0,True,False,False,True,False,False,False,False

In [451]:
pbp_2023[
    [
        'is_third_down',
        'is_third_and_long',
        'is_third_down_conversion',
        'is_third_and_long_conversion',
        'is_negative_epa',
        'is_panic_play',
        'is_redzone',
        'is_redzone_td'
    ]
].mean()

is_third_down                   0.279393
is_third_and_long               0.150554
is_third_down_conversion        0.100867
is_third_and_long_conversion    0.038084
is_negative_epa                 0.553779
is_panic_play                   0.063216
is_redzone                      0.128984
is_redzone_td                   0.024940
dtype: float64

In [452]:
pbp_2023['player_id'].nunique()

119

In [453]:
pbp_2023.describe()

,season,qb_epa,down,qb_dropback,third_down_converted,ydstogo,yardline_100,pass_touchdown
count,20770.0,20770.000000,20693.000000,20770.0,20770.000000,20770.000000,20770.000000,20770.000000
mean,2023.0,0.015803,1.967960,1.0,0.100867,8.812133,52.312566,0.036302
std,0.0,1.573816,0.863812,0.0,0.301159,4.013045,23.481679,0.187046
min,2023.0,-12.443874,1.000000,1.0,0.000000,0.000000,1.000000,0.000000
25%,2023.0,-0.776483,1.000000,1.0,0.000000,6.000000,35.000000,0.000000
50%,2023.0,-0.200559,2.000000,1.0,0.000000,10.000000,56.000000,0.000000
75%,2023.0,0.904763,3.000000,1.0,0.000000,10.000000,72.000000,0.000000
max,2023.0,8.882384,4.000000,1.0,1.000000,37.000000,99.000000,1.000000

In [454]:
pbp_2023

,player_id,season,qb_epa,play_type,down,qb_dropback,third_down_converted,ydstogo,yardline_100,pass_touchdown,is_third_down,is_third_and_long,is_third_and_long_conversion,is_third_down_conversion,is_negative_epa,is_panic_play,is_redzone,is_redzone_td
3,00-0037077,2023,0.703308,pass,2.0,1.0,0.0,7.0,72.0,0.0,False,False,False,False,False,False,False,False
5,00-0037077,2023,-0.521544,pass,1.0,1.0,0.0,10.0,64.0,0.0,False,False,False,False,True,False,False,False
6,00-0037077,2023,1.173155,pass,2.0,1.0,0.0,10.0,64.0,0.0,False,False,False,False,False,False,False,False
7,00-0037077,2023,-0.515452,pass,1.0,1.0,0.0,10.0,52.0,0.0,False,False,False,False,True,False,False,False
8,00-0037077,2023,-0.872005,pass,2.0,1.0,0.0,9.0,51.0,0.0,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47375,00-0039150,2023,0.351918,pass,2.0,1.0,0.0,6.0,59.0,0.0,False,False,False,False,False,False,False,False
47378,00-0039150,2023,-0.230056,pass,1.0,1.0,0.0,10.0,52.0,0.0,False,False,False,False,True,False,False,False
47379,00-0039150,2023,1.611585,run,2.0,1.0,0.0,6.0,48.0,0.0,False,False,False,False,False,False,False,False
47381,00-0039150,2023,-5.466342,pass,1.0,1.0,0.0,15.0,33.0,0.0,False,False,False,False,True,False,False,False
47391,00-0034855,2023,1.995936,pass,3.0,1.0,1.0,5.0,36.0,0.0,True,False,False,True,False,False,False,False

In [455]:
advanced_metrics = (
    pbp_2023.groupby(
        ['player_id', 'season'],
        as_index=False
    )
    .agg(
        total_negative_epa_plays = ("is_negative_epa", "sum"),
        total_panic_plays = ("is_panic_play", "sum"),
        total_third_downs = ("is_third_down", "sum"),
        total_third_downs_converted = ("is_third_down_conversion", "sum"),
        total_dropbacks = ("qb_dropback", "count"),
        total_third_and_long = ("is_third_and_long", "sum"),
        total_third_and_long_converted = ("is_third_and_long_conversion", "sum"),
        total_redzone_attempts = ("is_redzone", "sum"),
        total_redzone_tds = ("is_redzone_td", "sum")
    )
)

In [456]:
advanced_metrics

,player_id,season,total_negative_epa_plays,total_panic_plays,total_third_downs,total_third_downs_converted,total_dropbacks,total_third_and_long,total_third_and_long_converted,total_redzone_attempts,total_redzone_tds
0,00-0023459,2023,2,0,0,0,2,0,0,0,0
1,00-0026158,2023,120,17,54,16,213,33,8,28,5
2,00-0026498,2023,304,28,150,58,565,72,20,89,18
3,00-0026625,2023,24,1,12,4,43,3,1,8,0
4,00-0027114,2023,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
114,00-0039040,2023,1,0,0,0,1,0,0,0,0
115,00-0039150,2023,389,55,189,55,620,114,19,56,11
116,00-0039152,2023,172,23,90,25,291,54,9,26,4
117,00-0039163,2023,296,33,172,66,557,91,25,73,16
118,00-0039164,2023,56,10,26,8,100,16,1,11,1

In [457]:
#Filter by dropbacks to remove any outliers 
advanced_metrics = advanced_metrics[advanced_metrics['total_dropbacks'] >= 150]

In [458]:
advanced_metrics

,player_id,season,total_negative_epa_plays,total_panic_plays,total_third_downs,total_third_downs_converted,total_dropbacks,total_third_and_long,total_third_and_long_converted,total_redzone_attempts,total_redzone_tds
1,00-0026158,2023,120,17,54,16,213,33,8,28,5
2,00-0026498,2023,304,28,150,58,565,72,20,89,18
7,00-0028118,2023,123,10,68,23,218,33,7,21,2
10,00-0029263,2023,297,30,143,46,527,76,18,89,20
11,00-0029604,2023,176,13,91,36,329,44,15,52,12
13,00-0029701,2023,160,21,84,25,268,47,10,31,3
16,00-0030565,2023,283,35,159,55,548,81,20,79,16
17,00-0031280,2023,320,48,178,64,590,99,29,77,17
19,00-0031345,2023,101,4,53,20,191,19,7,24,6
22,00-0031800,2023,87,11,50,19,155,27,6,9,2
23,00-0032156,2023,110,12,47,9,167,31,3,18,1
29,00-0033077,2023,323,25,175,78,658,79,26,124,28
30,00-0033106,2023,325,34,162,65,643,82,22,91,19
33,00-0033319,2023,92,6,41,14,164,28,9,20,3
35,00-0033537,2023,121,15,62,23,204,40,10,23,6
40,00-0033873,2023,344,40,172,70,672,99,29,107,24
43,00-0033949,2023,287,39,147,55,484,77,21,59,11
53,00-0034796,2023,283,31,139,52,560,73,18,78,17
54,00-0034855,2023,353,40,206,84,639,110,30,79,14
55,00-0034857,2023,318,30,161,66,652,85,24,93,20
59,00-0035100,2023,148,16,73,30,284,41,11,42,8
60,00-0035228,2023,176,19,81,30,305,49,13,40,8
63,00-0035282,2023,114,9,52,16,196,23,4,17,2
64,00-0035289,2023,316,40,147,47,548,76,17,76,10
68,00-0035710,2023,127,18,54,19,211,33,6,19,2
72,00-0036212,2023,303,34,173,74,605,88,27,86,17
73,00-0036264,2023,339,41,178,78,633,94,30,111,25
76,00-0036355,2023,279,33,143,58,517,76,23,77,15
77,00-0036389,2023,331,28,151,68,623,82,26,66,13
80,00-0036442,2023,212,21,102,38,402,54,12,53,11
88,00-0036945,2023,276,28,139,50,459,82,24,66,11
90,00-0036971,2023,341,40,163,61,643,79,18,71,13
91,00-0036972,2023,216,23,107,32,380,52,11,33,8
92,00-0037013,2023,273,31,130,35,438,74,12,46,6
93,00-0037077,2023,415,44,180,60,711,102,25,73,13
98,00-0037834,2023,219,24,119,54,486,68,25,76,19
99,00-0038102,2023,214,28,124,41,361,67,17,34,3
100,00-0038108,2023,163,22,72,14,246,45,5,12,5
102,00-0038122,2023,233,32,123,48,439,73,21,57,9
106,00-0038416,2023,81,11,46,20,160,24,7,21,3
107,00-0038476,2023,158,27,78,15,237,57,9,17,6
108,00-0038579,2023,213,21,107,34,367,50,13,52,8
115,00-0039150,2023,389,55,189,55,620,114,19,56,11
116,00-0039152,2023,172,23,90,25,291,54,9,26,4
117,00-0039163,2023,296,33,172,66,557,91,25,73,16

In [459]:
advanced_metrics.shape

(45, 11)

In [460]:
#Compute advanced stats
advanced_metrics['negative_epa_rate'] = advanced_metrics['total_negative_epa_plays'] / advanced_metrics['total_dropbacks']
advanced_metrics['panic_play_rate'] = advanced_metrics['total_panic_plays'] / advanced_metrics['total_dropbacks']
advanced_metrics['third_down_conversion_rate'] = advanced_metrics['total_third_downs_converted'] / advanced_metrics['total_third_downs']
advanced_metrics['third_and_long_conversion_rate'] = advanced_metrics['total_third_and_long_converted'] / advanced_metrics['total_third_and_long']
advanced_metrics['third_down_regular_attempts'] = advanced_metrics["total_third_downs"] - advanced_metrics["total_third_and_long"]
advanced_metrics['third_down_regular_conversions'] = advanced_metrics["total_third_downs_converted"] - advanced_metrics["total_third_and_long_converted"]
advanced_metrics['third_down_regular_conversion_rate'] = advanced_metrics["third_down_regular_conversions"] / advanced_metrics["third_down_regular_attempts"]
advanced_metrics['redzone_td_rate'] = advanced_metrics['total_redzone_tds'] / advanced_metrics['total_redzone_attempts']

/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['negative_epa_rate'] = advanced_metrics['total_negative_epa_plays'] / advanced_metrics['total_dropbacks']
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['panic_play_rate'] = advanced_metrics['total_panic_plays'] / advanced_metrics['total_dropbacks']
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['third_down_conversion_rate'] = advanced_metrics['total_third_downs_converted'] / advanced_metrics['total_third_downs']
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['third_and_long_conversion_rate'] = advanced_metrics['total_third_and_long_converted'] / advanced_metrics['total_third_and_long']
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['third_down_regular_attempts'] = advanced_metrics["total_third_downs"] - advanced_metrics["total_third_and_long"]
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['third_down_regular_conversions'] = advanced_metrics["total_third_downs_converted"] - advanced_metrics["total_third_and_long_converted"]
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['third_down_regular_conversion_rate'] = advanced_metrics["third_down_regular_conversions"] / advanced_metrics["third_down_regular_attempts"]
/var/folders/dk/cx8zjc5x3bs4t_w02hzy6ylc0000gn/T/ipykernel_3755/3218933746.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  advanced_metrics['redzone_td_rate'] = advanced_metrics['total_redzone_tds'] / advanced_metrics['total_redzone_attempts']

In [461]:
advanced_metrics

,player_id,season,total_negative_epa_plays,total_panic_plays,total_third_downs,total_third_downs_converted,total_dropbacks,total_third_and_long,total_third_and_long_converted,total_redzone_attempts,total_redzone_tds,negative_epa_rate,panic_play_rate,third_down_conversion_rate,third_and_long_conversion_rate,third_down_regular_attempts,third_down_regular_conversions,third_down_regular_conversion_rate,redzone_td_rate
1,00-0026158,2023,120,17,54,16,213,33,8,28,5,0.563380,0.079812,0.296296,0.242424,21,8,0.380952,0.178571
2,00-0026498,2023,304,28,150,58,565,72,20,89,18,0.538053,0.049558,0.386667,0.277778,78,38,0.487179,0.202247
7,00-0028118,2023,123,10,68,23,218,33,7,21,2,0.564220,0.045872,0.338235,0.212121,35,16,0.457143,0.095238
10,00-0029263,2023,297,30,143,46,527,76,18,89,20,0.563567,0.056926,0.321678,0.236842,67,28,0.417910,0.224719
11,00-0029604,2023,176,13,91,36,329,44,15,52,12,0.534954,0.039514,0.395604,0.340909,47,21,0.446809,0.230769
13,00-0029701,2023,160,21,84,25,268,47,10,31,3,0.597015,0.078358,0.297619,0.212766,37,15,0.405405,0.096774
16,00-0030565,2023,283,35,159,55,548,81,20,79,16,0.516423,0.063869,0.345912,0.246914,78,35,0.448718,0.202532
17,00-0031280,2023,320,48,178,64,590,99,29,77,17,0.542373,0.081356,0.359551,0.292929,79,35,0.443038,0.220779
19,00-0031345,2023,101,4,53,20,191,19,7,24,6,0.528796,0.020942,0.377358,0.368421,34,13,0.382353,0.250000
22,00-0031800,2023,87,11,50,19,155,27,6,9,2,0.561290,0.070968,0.380000,0.222222,23,13,0.565217,0.222222
23,00-0032156,2023,110,12,47,9,167,31,3,18,1,0.658683,0.071856,0.191489,0.096774,16,6,0.375000,0.055556
29,00-0033077,2023,323,25,175,78,658,79,26,124,28,0.490881,0.037994,0.445714,0.329114,96,52,0.541667,0.225806
30,00-0033106,2023,325,34,162,65,643,82,22,91,19,0.505443,0.052877,0.401235,0.268293,80,43,0.537500,0.208791
33,00-0033319,2023,92,6,41,14,164,28,9,20,3,0.560976,0.036585,0.341463,0.321429,13,5,0.384615,0.150000
35,00-0033537,2023,121,15,62,23,204,40,10,23,6,0.593137,0.073529,0.370968,0.250000,22,13,0.590909,0.260870
40,00-0033873,2023,344,40,172,70,672,99,29,107,24,0.511905,0.059524,0.406977,0.292929,73,41,0.561644,0.224299
43,00-0033949,2023,287,39,147,55,484,77,21,59,11,0.592975,0.080579,0.374150,0.272727,70,34,0.485714,0.186441
53,00-0034796,2023,283,31,139,52,560,73,18,78,17,0.505357,0.055357,0.374101,0.246575,66,34,0.515152,0.217949
54,00-0034855,2023,353,40,206,84,639,110,30,79,14,0.552426,0.062598,0.407767,0.272727,96,54,0.562500,0.177215
55,00-0034857,2023,318,30,161,66,652,85,24,93,20,0.487730,0.046012,0.409938,0.282353,76,42,0.552632,0.215054
59,00-0035100,2023,148,16,73,30,284,41,11,42,8,0.521127,0.056338,0.410959,0.268293,32,19,0.593750,0.190476
60,00-0035228,2023,176,19,81,30,305,49,13,40,8,0.577049,0.062295,0.370370,0.265306,32,17,0.531250,0.200000
63,00-0035282,2023,114,9,52,16,196,23,4,17,2,0.581633,0.045918,0.307692,0.173913,29,12,0.413793,0.117647
64,00-0035289,2023,316,40,147,47,548,76,17,76,10,0.576642,0.072993,0.319728,0.223684,71,30,0.422535,0.131579
68,00-0035710,2023,127,18,54,19,211,33,6,19,2,0.601896,0.085308,0.351852,0.181818,21,13,0.619048,0.105263
72,00-0036212,2023,303,34,173,74,605,88,27,86,17,0.500826,0.056198,0.427746,0.306818,85,47,0.552941,0.197674
73,00-0036264,2023,339,41,178,78,633,94,30,111,25,0.535545,0.064771,0.438202,0.319149,84,48,0.571429,0.225225
76,00-0036355,2023,279,33,143,58,517,76,23,77,15,0.539652,0.063830,0.405594,0.302632,67,35,0.522388,0.194805
77,00-0036389,2023,331,28,151,68,623,82,26,66,13,0.531300,0.044944,0.450331,0.317073,69,42,0.608696,0.196970
80,00-0036442,2023,212,21,102,38,402,54,12,53,11,0.527363,0.052239,0.372549,0.222222,48,26,0.541667,0.207547
88,00-0036945,2023,276,28,139,50,459,82,24,66,11,0.601307,0.061002,0.359712,0.292683,57,26,0.456140,0.166667
90,00-0036971,2023,341,40,163,61,643,79,18,71,13,0.530327,0.062208,0.374233,0.227848,84,43,0.511905,0.183099
91,00-0036972,2023,216,23,107,32,380,52,11,33,8,0.568421,0.060526,0.299065,0.211538,55,21,0.381818,0.242424
92,00-0037013,2023,273,31,130,35,438,74,12,46,6,0.623288,0.070776,0.269231,0.162162,56,23,0.410714,0.130435
93,00-0037077,2023,415,44,180,60,711,102,25,73,13,0.583685,0.061885,0.333333,0.245098,78,35,0.448718,0.178082
98,00-0037834,2023,219,24,119,54,486,68,25,76,19,0.450617,0.049383,0.453782,0.367647,51,29,0.568627,0.250000
99,00-0038102,2023,214,28,124,41,361,67,17,34,3,0.592798,0.077562,0.330645,0.253731,57,24,0.421053,0.088235
100,00-0038108,2023,163,22,72,14,246,45,5,12,5,0.662602,0.089431,0.194444,0.111111,27,9,0.333333,0.416667
102,00-0038122,2023,233,32,123,48,439,73,21,57,9,0.530752,0.072893,0.390244,0.287671,50,27,0.540000,0.157895
106,00-0038416,2023,81,11,46,20,160,24,7,21,3,0.506250,0.068750,0.434783,0.291667,22,13,0.590909,0.142857
107,00-0038476,2023,158,27,78,15,237,57,9,17,6,0.666667,0.113924,0.192308,0.157895,21,6,0.285714,0.352941
108,00-0038579,2023,213,21,107,34,367,50,13,52,8,0.580381,0.057221,0.317757,0.260000,57,21,0.368421,0.153846
115,00-0039150,2023,389,55,189,55,620,114,19,56,11,0.627419,0.088710,0.291005,0.166667,75,36,0.480000,0.196429
116,00-0039152,2023,172,23,90,25,291,54,9,26,4,0.591065,0.079038,0.277778,0.166667,36,16,0.444444,0.153846
117,00-0039163,2023,296,33,172,66,557,91,25,73,16,0.531418,0.059246,0.383721,0.274725,81,41,0.506173,0.219178

In [462]:
advanced_metrics = advanced_metrics[['player_id','season','negative_epa_rate', 'panic_play_rate', 'third_down_regular_conversion_rate','third_down_conversion_rate', 'third_and_long_conversion_rate', 'redzone_td_rate']]

In [463]:
advanced_metrics

,player_id,season,negative_epa_rate,panic_play_rate,third_down_regular_conversion_rate,third_down_conversion_rate,third_and_long_conversion_rate,redzone_td_rate
1,00-0026158,2023,0.563380,0.079812,0.380952,0.296296,0.242424,0.178571
2,00-0026498,2023,0.538053,0.049558,0.487179,0.386667,0.277778,0.202247
7,00-0028118,2023,0.564220,0.045872,0.457143,0.338235,0.212121,0.095238
10,00-0029263,2023,0.563567,0.056926,0.417910,0.321678,0.236842,0.224719
11,00-0029604,2023,0.534954,0.039514,0.446809,0.395604,0.340909,0.230769
13,00-0029701,2023,0.597015,0.078358,0.405405,0.297619,0.212766,0.096774
16,00-0030565,2023,0.516423,0.063869,0.448718,0.345912,0.246914,0.202532
17,00-0031280,2023,0.542373,0.081356,0.443038,0.359551,0.292929,0.220779
19,00-0031345,2023,0.528796,0.020942,0.382353,0.377358,0.368421,0.250000
22,00-0031800,2023,0.561290,0.070968,0.565217,0.380000,0.222222,0.222222
23,00-0032156,2023,0.658683,0.071856,0.375000,0.191489,0.096774,0.055556
29,00-0033077,2023,0.490881,0.037994,0.541667,0.445714,0.329114,0.225806
30,00-0033106,2023,0.505443,0.052877,0.537500,0.401235,0.268293,0.208791
33,00-0033319,2023,0.560976,0.036585,0.384615,0.341463,0.321429,0.150000
35,00-0033537,2023,0.593137,0.073529,0.590909,0.370968,0.250000,0.260870
40,00-0033873,2023,0.511905,0.059524,0.561644,0.406977,0.292929,0.224299
43,00-0033949,2023,0.592975,0.080579,0.485714,0.374150,0.272727,0.186441
53,00-0034796,2023,0.505357,0.055357,0.515152,0.374101,0.246575,0.217949
54,00-0034855,2023,0.552426,0.062598,0.562500,0.407767,0.272727,0.177215
55,00-0034857,2023,0.487730,0.046012,0.552632,0.409938,0.282353,0.215054
59,00-0035100,2023,0.521127,0.056338,0.593750,0.410959,0.268293,0.190476
60,00-0035228,2023,0.577049,0.062295,0.531250,0.370370,0.265306,0.200000
63,00-0035282,2023,0.581633,0.045918,0.413793,0.307692,0.173913,0.117647
64,00-0035289,2023,0.576642,0.072993,0.422535,0.319728,0.223684,0.131579
68,00-0035710,2023,0.601896,0.085308,0.619048,0.351852,0.181818,0.105263
72,00-0036212,2023,0.500826,0.056198,0.552941,0.427746,0.306818,0.197674
73,00-0036264,2023,0.535545,0.064771,0.571429,0.438202,0.319149,0.225225
76,00-0036355,2023,0.539652,0.063830,0.522388,0.405594,0.302632,0.194805
77,00-0036389,2023,0.531300,0.044944,0.608696,0.450331,0.317073,0.196970
80,00-0036442,2023,0.527363,0.052239,0.541667,0.372549,0.222222,0.207547
88,00-0036945,2023,0.601307,0.061002,0.456140,0.359712,0.292683,0.166667
90,00-0036971,2023,0.530327,0.062208,0.511905,0.374233,0.227848,0.183099
91,00-0036972,2023,0.568421,0.060526,0.381818,0.299065,0.211538,0.242424
92,00-0037013,2023,0.623288,0.070776,0.410714,0.269231,0.162162,0.130435
93,00-0037077,2023,0.583685,0.061885,0.448718,0.333333,0.245098,0.178082
98,00-0037834,2023,0.450617,0.049383,0.568627,0.453782,0.367647,0.250000
99,00-0038102,2023,0.592798,0.077562,0.421053,0.330645,0.253731,0.088235
100,00-0038108,2023,0.662602,0.089431,0.333333,0.194444,0.111111,0.416667
102,00-0038122,2023,0.530752,0.072893,0.540000,0.390244,0.287671,0.157895
106,00-0038416,2023,0.506250,0.068750,0.590909,0.434783,0.291667,0.142857
107,00-0038476,2023,0.666667,0.113924,0.285714,0.192308,0.157895,0.352941
108,00-0038579,2023,0.580381,0.057221,0.368421,0.317757,0.260000,0.153846
115,00-0039150,2023,0.627419,0.088710,0.480000,0.291005,0.166667,0.196429
116,00-0039152,2023,0.591065,0.079038,0.444444,0.277778,0.166667,0.153846
117,00-0039163,2023,0.531418,0.059246,0.506173,0.383721,0.274725,0.219178

In [464]:
advanced_metrics.shape

(45, 8)

In [465]:
advanced_metrics = advanced_metrics.round({
    "negative_epa_rate": 3,
    "panic_play_rate": 3,
    "third_down_conversion_rate": 3,
    "third_and_long_conversion_rate": 3,
    "redzone_td_rate": 3
})

In [466]:
advanced_metrics.head(10)

,player_id,season,negative_epa_rate,panic_play_rate,third_down_regular_conversion_rate,third_down_conversion_rate,third_and_long_conversion_rate,redzone_td_rate
1,00-0026158,2023,0.563,0.080,0.380952,0.296,0.242,0.179
2,00-0026498,2023,0.538,0.050,0.487179,0.387,0.278,0.202
7,00-0028118,2023,0.564,0.046,0.457143,0.338,0.212,0.095
10,00-0029263,2023,0.564,0.057,0.417910,0.322,0.237,0.225
11,00-0029604,2023,0.535,0.040,0.446809,0.396,0.341,0.231
13,00-0029701,2023,0.597,0.078,0.405405,0.298,0.213,0.097
16,00-0030565,2023,0.516,0.064,0.448718,0.346,0.247,0.203
17,00-0031280,2023,0.542,0.081,0.443038,0.360,0.293,0.221
19,00-0031345,2023,0.529,0.021,0.382353,0.377,0.368,0.250
22,00-0031800,2023,0.561,0.071,0.565217,0.380,0.222,0.222

In [467]:
qb_master_2023 = pd.merge(qb_cortisol_scores, advanced_metrics, on=['player_id', 'season'], how="left")

In [468]:
qb_master_2023

,player_id,qb_name,season,team,turnover_score,drive_score,success_score,cortisol_score,rank,total_dropbacks,stabilized_cortisol_score,stabilized_rank,negative_epa_rate,panic_play_rate,third_down_regular_conversion_rate,third_down_conversion_rate,third_and_long_conversion_rate,redzone_td_rate
0,00-0037834,Brock Purdy,2023,SF,0.545681,0.958079,0.989908,100.0,1.0,472,77.074414,1,0.451,0.049,0.568627,0.454,0.368,0.250
1,00-0033077,Dak Prescott,2023,DAL,0.708394,0.814228,0.713894,89.0,2.0,629,73.848289,2,0.491,0.038,0.541667,0.446,0.329,0.226
2,00-0039163,C.J. Stroud,2023,HOU,0.828409,0.573352,0.646294,81.0,4.0,537,67.775762,3,0.531,0.059,0.506173,0.384,0.275,0.219
3,00-0036212,Tua Tagovailoa,2023,MIA,0.531509,0.855838,0.693101,77.4,5.0,589,66.327087,4,0.501,0.056,0.552941,0.428,0.307,0.198
4,00-0036264,Jordan Love,2023,GB,0.789353,0.544051,0.638463,76.2,6.0,609,65.822288,5,0.536,0.065,0.571429,0.438,0.319,0.225
5,00-0033106,Jared Goff,2023,DET,0.656490,0.709246,0.603776,73.7,7.0,635,64.549168,6,0.505,0.053,0.537500,0.401,0.268,0.209
6,00-0035100,Jake Browning,2023,CIN,0.635915,0.859304,0.668985,83.8,3.0,267,63.543462,7,0.521,0.056,0.593750,0.411,0.268,0.190
7,00-0031280,Derek Carr,2023,NO,0.735766,0.655903,0.480534,69.9,9.0,579,61.778334,8,0.542,0.081,0.443038,0.360,0.293,0.221
8,00-0034857,Josh Allen,2023,BUF,0.561562,0.595998,0.746123,68.4,11.0,603,61.070876,9,0.488,0.046,0.552632,0.410,0.282,0.215
9,00-0036355,Justin Herbert,2023,LAC,0.837863,0.494337,0.498117,69.5,10.0,485,60.696485,10,0.540,0.064,0.522388,0.406,0.303,0.195
10,00-0029604,Kirk Cousins,2023,MIN,0.582710,0.768455,0.621235,72.5,8.0,328,60.149573,11,0.535,0.040,0.446809,0.396,0.341,0.231
11,00-0034796,Lamar Jackson,2023,BAL,0.503985,0.678770,0.702382,66.4,12.0,494,59.072135,12,0.505,0.055,0.515152,0.374,0.247,0.218
12,00-0033873,Patrick Mahomes,2023,KC,0.681668,0.623289,0.489640,64.7,13.0,624,58.966493,13,0.512,0.060,0.561644,0.407,0.293,0.224
13,00-0026498,Matthew Stafford,2023,LA,0.745903,0.468302,0.551407,64.3,14.0,551,58.294626,14,0.538,0.050,0.487179,0.387,0.278,0.202
14,00-0030565,Geno Smith,2023,SEA,0.723691,0.503839,0.482579,60.9,16.0,530,56.221386,15,0.516,0.064,0.448718,0.346,0.247,0.203
15,00-0036442,Joe Burrow,2023,CIN,0.779268,0.536118,0.376526,60.9,15.0,389,55.385284,16,0.527,0.052,0.541667,0.373,0.222,0.208
16,00-0036389,Jalen Hurts,2023,PHI,0.500720,0.547121,0.670241,57.3,18.0,574,54.311180,17,0.531,0.045,0.608696,0.450,0.317,0.197
17,00-0035228,Kyler Murray,2023,ARI,0.732764,0.525462,0.414240,59.0,17.0,286,53.765144,18,0.577,0.062,0.531250,0.370,0.265,0.200
18,00-0034855,Baker Mayfield,2023,TB,0.602069,0.468655,0.537289,53.2,19.0,606,51.936470,19,0.552,0.063,0.562500,0.408,0.273,0.177
19,00-0026158,Joe Flacco,2023,CLE,0.589078,0.197451,0.631218,42.7,21.0,212,47.485766,20,0.563,0.080,0.380952,0.296,0.242,0.179
20,00-0029263,Russell Wilson,2023,DEN,0.470986,0.482395,0.539689,44.7,20.0,492,47.086647,21,0.564,0.057,0.417910,0.322,0.237,0.225
21,00-0036971,Trevor Lawrence,2023,JAX,0.505369,0.482746,0.451322,42.4,22.0,599,45.451941,22,0.530,0.062,0.511905,0.374,0.228,0.183
22,00-0038102,Kenny Pickett,2023,PIT,0.841884,0.242919,0.194730,39.8,24.0,347,45.273747,23,0.593,0.078,0.421053,0.331,0.254,0.088
23,00-0038579,Aidan O'Connell,2023,LV,0.677857,0.321331,0.335480,39.8,23.0,367,45.131016,24,0.580,0.057,0.368421,0.318,0.260,0.154
24,00-0029701,Ryan Tannehill,2023,TEN,0.574038,0.460208,0.262471,35.9,25.0,262,44.433065,25,0.597,0.078,0.405405,0.298,0.213,0.097
25,00-0033949,Joshua Dobbs,2023,ARI,0.586674,0.339958,0.246285,29.5,28.0,283,41.518871,26,0.593,0.081,0.485714,0.374,0.273,0.186
26,00-0038122,Desmond Ridder,2023,ATL,0.351829,0.519656,0.423849,31.8,26.0,419,40.699742,27,0.531,0.073,0.540000,0.390,0.288,0.158
27,00-0036945,Justin Fields,2023,CHI,0.455767,0.330824,0.447227,30.4,27.0,414,40.042370,28,0.601,0.061,0.456140,0.360,0.293,0.167
28,00-0035289,Gardner Minshew,2023,IND,0.508901,0.295075,0.369057,28.1,29.0,524,37.590139,29,0.577,0.073,0.422535,0.320,0.224,0.132
29,00-0039152,Will Levis,2023,TEN,0.479394,0.183142,0.371067,20.0,32.0,283,37.582561,30,0.591,0.079,0.444444,0.278,0.167,0.154
30,00-0038476,Tommy DeVito,2023,NYG,0.378552,0.257908,0.296818,12.8,33.0,215,37.009575,31,0.667,0.114,0.285714,0.192,0.158,0.353
31,00-0036972,Mac Jones,2023,NE,0.472045,0.379957,0.204338,21.1,31.0,367,36.183297,32,0.568,0.061,0.381818,0.299,0.212,0.242
32,00-0037077,Sam Howell,2023,WAS,0.528576,0.327470,0.308103,27.9,30.0,677,36.116239,33,0.584,0.062,0.448718,0.333,0.245,0.178
33,00-0038108,Bailey Zappe,2023,NE,0.483141,0.061743,0.116573,0.0,36.0,237,31.411129,34,0.663,0.089,0.333333,0.194,0.111,0.417
34,00-0037013,Zach Wilson,2023,NYJ,0.447457,0.156252,0.113675,2.4,35.0,414,25.801583,35,0.623,0.071,0.410714,0.269,0.162,0.130
35,00-0039150,Bryce Young,2023,CAR,0.580215,0.072853,0.038334,3.4,34.0,589,22.256308,36,0.627,0.089,0.480000,0.291,0.167,0.196

In [469]:
qb_master_2023.to_csv("../data/processed/qb_master_2023.csv")